### ISSUE TITLE
Use bundled busybox as Toybox replacement

### ISSUE THREAD

**Issue by dianlujitao** [opengapps/opengapps#211] opened 2016-01-02 11:35 UTC
toybox doesn't offer awk, but opengapps installer uses it.

**Comment by mfonville** [comment] 2016-01-11 13:56
Since rewriting all our lines from awk to sed would take quite an effort, I will look into the possibility of bundling our own gawk with the installer, just as we do with xzdec. It could be a temporary measure until Toybox would be posix-feature complete.

**Comment by dianlujitao** [comment] 2016-01-12 01:08
Thanks

**Comment by mfonville** [comment] 2016-01-13 15:04
I was able to compile gawk for both arm and x86. We could bundle that as a solution just like we do with xzdec.

**Comment by mfonville** [comment] 2016-01-13 16:11
@dianlujitao
Could you try our https://github.com/opengapps/opengapps/tree/bundledawk branch and report back to me whether it works for you with CM13 recovery?
I compiled a pico package for you: https://www.dropbox.com/s/ttw5f551gj15g0v/open_gapps-arm-6.0-pico-20160113.zip?dl=0

**Comment by sfan5** [comment] 2016-01-23 10:48
@mfonville 
I tried that branch and it didn't work either. Symlinking /sbin/awk to something else fails because of permissions.

After [fixing](https://gist.github.com/sfan5/bb7e957e69a557146a87) awk and 2 unrelated issues (missing : in LD_LIBRARY_PATH, head -c not working either) it installs but results in a broken CM installation.

**Comment by mfonville** [comment] 2016-01-23 10:52
@sfan5 thanks for the feedback.
In that case we will bundle a complete busybox instead to handle CM13 recovery.
Currently I am ill and not able to write any code. I hope to be able to work on it next week.

**Comment by levysantanna** [comment] 2016-02-02 20:39
I am still having this problem with the last packages. Do we have a kind of workaround? Can I help with something, some commit?

**Comment by sfan5** [comment] 2016-02-03 12:26
You can try a prebuilt *nano* package with my fixes applied: https://kitsunemimi.pw/tmp/open_gapps-arm-6.0-nano-20160124.zip
It doesn't work perfectly but it installs and kinda works.

After installing this you'll need to use adb to run <code>pm disable com.google.android.setupwizard</code>(as root IIRC) to disable the constantly crashing Setup Wizard app and you'll need to re-install all Google apps to get the new versions.

**Comment by klausenbusk** [comment] 2016-02-06 18:36
> In that case we will bundle a complete busybox instead to handle CM13 recovery.

If you don't know busybox can be downloaded from https://busybox.net/downloads/binaries/latest/ (already compiled).
busybox-armv7l works fine on my Samsung s4 mini in recovery mode (cm-13.0-20160206-NIGHTLY-serranoltexx-recovery.img)

**Comment by mfonville** [comment] 2016-02-06 18:55
@klausenbusk thanks! :-)

**Comment by klausenbusk** [comment] 2016-02-06 19:03
For anyone which miss awk.
Download https://busybox.net/downloads/binaries/latest/busybox-armv7l
```
adb push busybox-armv7l /sbin/awk
adb shell chmod +x /sbin/awk
```
Apply update

Voila
I just confirmed that it works! :)

**Comment by mfonville** [comment] 2016-02-06 19:56
@klausenbusk would you do me a favour and could you post the /cache/recovery/log of CM13 recovery for me online? :-)
I would like to be able to add detection of the CM13 recovery to our scripts; but I need an example and lack the time to replace recovery on my own device at the moment.

**Comment by klausenbusk** [comment] 2016-02-06 20:15
> @klausenbusk would you do me a favour and could you post the /cache/recovery/log of CM13 recovery for me online? :-)

/system/build.prop http://sprunge.us/MJYV

**Comment by klausenbusk** [comment] 2016-02-06 20:45
Working on a patch at the moment.

**Comment by mfonville** [comment] 2016-02-06 21:07
@klausenbusk do you have the **/cache/recovery/log** instead of the build.prop? That exposes the recovery for me (not the ROM!) :-)

**Comment by klausenbusk** [comment] 2016-02-06 21:09
@mfonville  nope.. I will create a pr in 5 min.

**Comment by mfonville** [comment] 2016-02-06 21:11
@klausenbusk Well, if you do find time at a later moment to fetch it from your device (it should be available the moment you log in to the recovery) it would be a great help
For the PR; you can take a look at something @osm0sis had suggested: https://github.com/osm0sis/AnyKernel2/commit/19b056b9ddaca6284a6fa308f7021385a5d0a4a2
lines 70 to 74 are a neat trick.

**Comment by klausenbusk** [comment] 2016-02-06 21:15
Give it a look :)

**Comment by mfonville** [comment] 2016-02-06 21:30
@klausenbusk I did; I have some feedback and suggestions. Looks very good and can probably be merged very soon (we should run some field tests first or course).

**Comment by mfonville** [comment] 2016-02-06 23:26
I still need the CM13 recovery detection; for that I need a CM13 recovery log file.
After the bundled busybox solution this is ready to go mainline

**Comment by klausenbusk** [comment] 2016-02-06 23:33
> I still need the CM13 recovery detection; for that I need a CM13 recovery log file.

Why do we need CM13 detection?

**Comment by mfonville** [comment] 2016-02-06 23:34
Because users *will* report errors in the forums and various places, and we need to see which recovery they use, since that is one of the most major factors that influences issues.

**Comment by klausenbusk** [comment] 2016-02-06 23:39
> Because users will report errors in the forums and various places, and we need to see which recovery they use, since that is one of the most major factors that influences issues.

Can't you just use the variable rom_android_version? Which we already define: https://github.com/opengapps/opengapps/blob/master/scripts/inc.updatebinary.sh#L479 For mine recovery it is: 6.0.1

**Comment by mfonville** [comment] 2016-02-06 23:41
Nope; Recovery is something completely different than the ROM. You can combine any recovery with any ROM (they are i.e. on separate partitions and boot independent of one another).
So the ROM gives 0% information for us.

**Comment by dianlujitao** [comment] 2016-02-07 00:56
Hello @mfonville , it's better for you to detect if busybox exists instead of detect the recovery variant. If you set TW_USE_TOOLBOX := true when compiling TWRP, busybox won't be available too

**Comment by mfonville** [comment] 2016-02-07 01:12
Current implementation always starts up our own busybox environment

**Comment by dianlujitao** [comment] 2016-02-07 01:15
That should be okay

**Comment by osm0sis** [comment] 2016-02-07 01:40
The log already captures recovery name. Though my parsing was kinda hackish there so it could use an update probably

**Comment by mfonville** [comment] 2016-02-07 09:05
Afaik the current parsing finds it to be a cwm-based recovery. But it is quite deviates from original cwm so identifying it as a separate entry is the most practical.

**Comment by osm0sis** [comment] 2016-02-07 11:29
Gotcha. cat /sbin/recovery might reveal it if the log doesn't. :+1:

**Comment by mfonville** [comment] 2016-02-07 11:40
I got a patch ready and uploaded to the busybox branch to recognize CM recovery; it needs some testing though.

**Comment by mfonville** [comment] 2016-02-07 12:02
I tested my recovery-detection; and at least that works. But new problems ahead:
The busybox solution itself does not seem to work yet in CM13 recovery.
1) it doesn't find the gapps-config file (located in the same folder as the zip)
2) installation of all applications fail; so I expect either a problem with the zip (maybe our original zip parameter does not get correctly passed through in CM recovery?), the tar or the xz decompression.

**Comment by mfonville** [comment] 2016-02-07 13:24
Ok; I caught a couple of mistakes we made. Time for testing again.

**Comment by mfonville** [comment] 2016-02-07 20:35
@osm0sis it doesn't help whatever I try, but `ln -s` gives on any location (even a self-spawned tmpfs) always a permission denied in the toybox shell :-(

**Comment by osm0sis** [comment] 2016-02-07 20:51
Works on AK2.. Did you chmod -R /tmp/bin first?

**Comment by mfonville** [comment] 2016-02-07 21:00
@osm0sis yes, also with chmod -R 755 on /tmp/bin :-(
I am totally clueless what causes it; it looks as if symlink is just broken in i9300 CM13 recovery of today.

**Comment by osm0sis** [comment] 2016-02-08 01:07
I'll try CMR on my flo again tomorrow and see if I can reproduce the issue.

**Comment by osm0sis** [comment] 2016-02-08 15:58
Have you verified the busybox binary you're using works at all?

I'm using the latest CMR for flo (http://mirrors.reflected.net/pub/get.cm/jenkins/148254/) and my own busybox build (arm for flo) and..

> root@flo:/tmp # ln
> usage: ln [-sfnv] [FROM...] TO
> 
> Create a link between FROM and TO.
> With only one argument, create link in current directory.
> 
> -s      Create a symbolic link
> -f      Force the creation of the link, even if TO already exists
> -n      Symlink at destination treated as file
> -v      Verbose
> 
> ln: Needs 1 argument

CMR's "ln" appears to work fine..

`mkdir /tmp/bin;
chmod 755 /tmp/busybox /tmp/bin;
bb=/tmp/busybox;
for i in $($bb --list); do
  ln -s $bb /tmp/bin/$i;
done;`

This properly creates the /tmp/bin/* symlinks to all busybox applets..

> root@flo:/tmp/bin # PATH="/tmp/bin:$PATH" $bb ash;
> /tmp/bin # ls --help
> BusyBox v1.24.1-osm0sis (2016-02-05 15:38:29 AST) multi-call binary.
> 
> Usage: ls [-1AaCxdLHRFplinsehrSXvctu] [-w WIDTH] [FILE]...

And executing a shell with the commandline PATH override works perfectly.

**Comment by mfonville** [comment] 2016-02-08 16:01
The busybox binary itself works perfectly.
Also it works in TWRP, but not in CM Recovery Toybox for me.
I think it is related to tmpfs and the stickybit not settable on it.
And later I thought that my experiments to try to put in on /cache where flawed because /cache would not be mounted (ergo still tmpfs).
I will do some extra testing.

My worst fear is that it might just be that there are faulty CM recoveries floating around :-/

**Comment by osm0sis** [comment] 2016-02-08 16:07
It's possible.. and following from a Chainfire school-of-thought, the workaround for a faulty recovery would be to fallback to using system's ln with the LD_LIBRARY_PATH=/system/lib override

I still feel like you might be missing something though, you should be able to create the symlinks with busybox itself if the permissions and everything are right. I just did so myself to test.

**Comment by mfonville** [comment] 2016-02-08 16:37
Even with LD_LIBRARY_PATH specified, umount /cache + mount /cache, mount /system
It always ends with a Permission denied :-(
I am using this recovery to test with: https://download.cyanogenmod.org/get/jenkins/148142/cm-13.0-20160206-NIGHTLY-i9300-recovery.img

**Comment by osm0sis** [comment] 2016-02-08 17:11
Working fine using your pre-compiled busybox 1.21.1 and everything..

```
mkdir /tmp/bin;
chmod -R 755 /tmp/busybox /tmp/bin;
bb=/tmp/busybox;
for i in $($bb --list); do
  $bb ln -s $bb /tmp/bin/$i;
done;
PATH="/tmp/bin:$PATH" $bb ash;
```

No issues with LD overrides either..

> root@flo:/tmp # mount -o ro /system
> root@flo:/tmp # LD_LIBRARY_PATH=/system/lib /system/bin/ln --help
> usage: ln [-sfnv] [FROM...] TO
> 
> Create a link between FROM and TO.
> With only one argument, create link in current directory.
> 
> -s      Create a symbolic link
> -f      Force the creation of the link, even if TO already exists
> -n      Symlink at destination treated as file
> -v      Verbose

**Comment by klausenbusk** [comment] 2016-02-08 19:27
I think i have the same recovery on my fqthers s4 mini, no problem at all. But i only did the awk "hack". On smartphone, so writing is slow :)

Date: Mon, 8 Feb 2016 11:17:47 -0800

**Comment by dianlujitao** [comment] 2016-02-09 09:40
Just built the latest busybox branch, not work.
log: http://paste.ubuntu.com/15000942/
I **guess** the bundled busybox isn't working, still missing awk
I use TWRP 3.0 with toybox

**Comment by klausenbusk** [comment] 2016-02-09 09:51
> Just built the latest busybox branch, not work.
> log: http://paste.ubuntu.com/15000942/
> I guess the bundled busybox isn't working, still missing awk
> I use TWRP 3.0 with toybox

Do https://github.com/opengapps/opengapps/issues/211#issuecomment-180839428 work?

**Comment by dianlujitao** [comment] 2016-02-09 10:04
works well

**Comment by mfonville** [comment] 2016-02-11 23:01
@dianlujitao cut is not a proper replacement for most awk commands; since we do relatively complicated manipulations in some places.

@klausenbusk @osm0sis I retried today with CM feb 10 on my i9300; still the very same errors.
I really want to find the cause of this issue :-/

**Comment by klausenbusk** [comment] 2016-02-11 23:13
> @klausenbusk @osm0sis I retried today with CM feb 10 on my i9300; still the very same errors.
> I really want to find the cause of this issue :-/

Is /tmp mounted with noexec? or something similar?

**Comment by mfonville** [comment] 2016-02-12 16:44
I collected the contents /proc/mounts:
```
rootfs / rootfs rw,seclabel 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /tmp tmpfs rw,seclabel,relatime 0 0
tmpfs /storage tmpfs rw,seclabel,relatime,mode=050,gid=1028 0 0
/dev/fuse /sideload fuse ro,nosuid,nodev,noexec,relatime,user_id=0,group_id=0,allow_other,max_read=65536 0 0
/dev/block/mmcblk0p8 /cache ext4 rw,seclabel,nosuid,nodev,noatime,errors=panic,user_xattr,barrier=1,journal_async_commit,data=ordered 0 0
/dev/block/mmcblk0p9 /system ext4 rw,seclabel,relatime,user_xattr,barrier=1,data=ordered 0 0
```

**Comment by mfonville** [comment] 2016-02-12 23:07
I was able to overcome my permission-issues by enabling ADB debugging *within* the OS itself :-/
Which is weird, since as power user one expects recovery and OS (especially for AOSP-based builds) to at least separate those two worlds.

A new issue we are facing: toybox only understands `#!/sbin/sh` as hashbang while busybox uses that as a hint to only use strict `sh`-style interpreting and gives an error when it sees the bashims.
So probably we would have to separate update-binary with the busybox call and the actual installer.

**Comment by mfonville** [comment] 2016-02-15 18:31
Today I splitted out update-binary and the installer script; I am now testing whether it correctly works within CM-Recovery.
If it does work, I will merge it into master ASAP

**Closed** 2016-02-15 19:32 UTC
Labels: in progress

**Comment by dianlujitao** [comment] 2016-02-19 06:42
@mfonville Still not working.

/tmp/recovery.log shows
> Archive:  /sdcard/open_gapps-arm64-6.0-pico-20160219.zip
signed by SignApk
 extracting: /tmp/busybox            
/tmp/updater[25]: install: not found
ln: cannot create symbolic link from '/tmp/busybox' to '/tmp/bin/[': No such file or directory
ln: /tmp/bin/[: No such file or directory
ERROR 10: Failed to set-up busybox
Please use TWRP as recovery instead

**Comment by AlgernonD** [comment] 2017-08-28 07:50
Is there a package for this fix?

**Comment by mfonville** [comment] 2017-10-04 12:04
@AlgernonD bundling our own busybox is the fix, until maybe many more years in the future, since the broken recoveries will be around for a long time
