### ISSUE TITLE
Installing OpenGapps fails on lineageos 16 with error code 20

### ISSUE THREAD

**Issue by bhaskarmurthy** [opengapps/opengapps#755] opened 2019-07-30 16:49 UTC
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [ ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [ ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

Installing OpenGapps on LineageOS 16.0 fails with `error 20`
ROM Version: 16.1.0 (SDK 27)

**Reproduction Steps:**

1. Boot into TWRP
2. ADB sideload lineageOS
3. ADB sideload opengapps-nano

**Expected behavior:**

Gapps installed

**Observed behavior:**

Install fails with error code 20

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by m-fonseca** [comment] 2019-08-03 16:20
I'm also having this issue.  Just quickly poking around makes me think its not correctly mounting/finding the /system mount point.   There is also a segfault in there.  Not sure if thats the main cause and problem is just a symptom of that.

For me I'm trying this on a oneplus 6.  TWRP 3.3.1-2, lineageOS lineage-16.0-20190730-nightly-enchilada, open_gapps-arm64-9.0-full-20190803.  (i tried a few gapps, but they all fail)
-----
/tmp/recovery.log

I:TWFunc::Set_Brightness: Setting brightness control to 420
I:Set overlay: ''
I:Set page: 'install'
I:Set page: 'flash_confirm'
I:Set page: 'flash_zip'
I:operation_start: 'Flashing'
I:Unable to find a directory to store TWRP logs.Installing zip file '/sdcard/open_gapps-arm64-9.0-full-20190803.zip'
Checking for Digest file...
I:Update binary zip
Verifying package compatibility...
Package doesn't contain compatibility.zip entry
I:Extracting updater binary 'META-INF/com/google/android/update-binary'
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment not used in updater.
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: app_densities.txt
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: app_sizes.txt
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: bkup_tail.sh
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: gapps-remove.txt
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: g.prop
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: installer.sh
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: busybox-arm
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: tar-arm
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: unzip-arm
Archive:  /sdcard/open_gapps-arm64-9.0-full-20190803.zip
  inflating: zip-arm
libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 1402 (install), pid 1402 (install)
Segmentation fault
 
##############################
  _____   _____   ___   ____  
 /  _  \ |  __ \ / _ \ |  _ \ 
|  / \  || |__) | |_| || | \ \
| |   | ||  ___/|  __/ | | | |
|  \ /  || |    \ |__  | | | |
 \_/ \_/ |_|     \___| |_| |_|
       ___   _   ___ ___  ___ 
      / __| /_\ | _ \ _ \/ __|
     | (_ |/ _ \|  _/  _/\__ \
      \___/_/ \_\_| |_|  |___/
##############################
 
Open GApps full 9.0 - 20190803
 
- Mounting  /vendor
 
find: /system/system: No such file or directory
ls: /system/system: No such file or directory
- Gathering device & ROM information
 
*** Incompatible Android ROM detected ***
 
This GApps pkg is for Android 9.0.x ONLY
Please download the correct version for
your ROM: 16.1.0 (SDK 27)
 
******* GApps Installation failed *******
 
- Copying Log to /sdcard
 
- NO changes were made to your device
 
Installer will now exit...
 
Error Code: 20
cp: can't stat '': No such file or directory
ls: /system/system: No such file or directory
cp: can't stat '/system/system/etc/g.prop': No such file or directory
cp: can't stat '/system/system/default.prop': No such file or directory
cp: can't stat '/system/system/build.prop': No such file or directory
cp: can't stat '/vendor/vendor/build.prop': No such file or directory
cp: can't stat '/data/local.prop': No such file or directory
cp: can't stat '/build.prop': No such file or directory
cp: can't stat '/system/system/addon.d/70-gapps.sh': No such file or directory
cp: can't stat '/cache/recovery/log': No such file or directory
/tmp/installer.sh: line 1: logcat: not found
- Unmounting  /vendor
 
Updater process ended with ERROR: 20
I:Install took 8 second(s).
Error installing zip file '/sdcard/open_gapps-arm64-9.0-full-20190803.zip'
Updating partition details...
I:Data backup size is 0MB, free: 110684MB.
I:Unable to mount '/usbstorage'
I:Actual block device: '', current file system: 'vfat'
...done
I:Set page: 'flash_done'
I:operation_end - status=1

**Comment by pefi-github** [comment] 2019-09-11 10:08
Hi Bhaskar,
I could easily solve this problem by only installing Lineage OS, rebooting the system, restarting into recovery, giving a factory reset and finally installing GApps via USB or sdcard or any suitable place you could copy your GApps.
Reboot your system and there you are.
Greetings from Germany

**Comment by jmdavis** [comment] 2019-09-20 08:11
With open_gapps-arm64-9.0-pico-20190920.zip on lineage-16.0-20190919-nightly-guacamole-signed.zip, I get error 64 when trying to install opengapps. Older versions of opengapps gave a variety of different errors, and several claimed that the device was arm instead of arm64. I did not find any version that installed properly.

However, I can confirm that installing LineageOS, then rebooting the system into LineageOS (I didn't go past the first screen to set up anything), then rebooting into the bootloader so that I could fastboot into TWRP (which installing LineageOS removed), then doing a factory reset, and then installing the 2019-09-20 build of opengapps works (along with installing TWRP and the add-on for root access). However, it didn't work if I let TWRP install itself when rebooting like it wanted to (whereas the .zip did work).

So, I was able to get it to work eventually thanks to the suggestion by pefi-github and way too many attempts, but it really should work to just install opengapps at the same time as the ROM.

**Comment by pefi-github** [comment] 2019-09-20 12:20
Hi jmdavis, your are right, in the past it mostly worked fine by installing GApps right after linageos roms even using one recovery session. 
We have to consider that our smartphones have become more and more complex to setup and to program. So I'm thankful that we always will find solutions to get it run anyway - and that's for free.
But if you mastered it to install one of those nightlies and GApps successfully you only have to apply further nightlies via updater. It does it now as a background process. And there isn't any need for installing GApps again.
Greetings from Germany

**Comment by nezorflame** [comment] 2019-09-27 20:40
We've merged the mounting changes which should potentially fix the problem.
See if the new builds changed it for you.

**Comment by nickd03** [comment] 2019-10-01 14:36
i've been receiving email updates for these threads for years. i've tried unsubscribing, unwatching, muting and everything. they. wont. stop. its been a great long time but i need to stop receiving these emails lol. somebody help

**Comment by nickd03** [comment] 2019-10-01 18:30
i have definitely tried that many times but it just reverts back. i purposelly joined the mailing list a looong time ago but i'd like to leave it

**Comment by kevinoid** [comment] 2019-12-13 04:33
> We've merged the mounting changes which should potentially fix the problem.
> See if the new builds changed it for you.

Thanks @nezorflame!  Unfortunately, I just encountered this issue while [installing LineageOS 16.0 on sailfish](https://wiki.lineageos.org/devices/sailfish/install).

Using [`twrp-3.3.0-0-sailfish.img`](https://dl.twrp.me/sailfish/twrp-3.3.0-0-sailfish.img.html) (the latest workable version on sailfish due to TeamWin/android_device_google_sailfish#4) after sideloading [`lineage-16.0-20191211-nightly-sailfish-signed.zip`](https://mirrorbits.lineageos.org/full/sailfish/20191211/lineage-16.0-20191211-nightly-sailfish-signed.zip) I attempted to sideload [`open_gapps-arm64-9.0-nano-20191213.zip`](https://master.dl.sourceforge.net/project/opengapps/arm64/20191213/open_gapps-arm64-9.0-nano-20191213.zip), which failed with `Error Code: 20` preceded by `SIGSEGV` of `install` and other errors similar to https://github.com/opengapps/opengapps/issues/755#issuecomment-517936599

<details>
<summary><code>/tmp/recovery.log</code></summary>

    I:operation_start: 'Sideload'
    I:Unable to find a directory to store TWRP logs.Starting ADB sideload feature...
    E:[MTP] request read returned -1, errno: 5, exiting MtpServer::run loop
    I:Disabling MTP
    Stopping adbd...
    adbd pid 545 found, sending kill.
    I:Setting active slot B
    I:Lun file '/sys/class/android_usb/android0/f_mass_storage/lun0/file' does not exist, USB storage mode disabled
    TW_INCLUDE_CRYPTO := true
    I:Found brightness file at '/sys/class/leds/lcd-backlight/brightness'
    I:Got max brightness 255 from '/sys/class/leds/lcd-backlight/max_brightness'
    I:TWFunc::Set_Brightness: Setting brightness control to 80
    I:LANG: en
    I:AB_OTA_UPDATER := true
    sideload-host file size 183567260 block size 65536
    Installing zip file '/sideload/package.zip'
    I:Update binary zip
    Verifying package compatibility...
    Package doesn't contain compatibility.zip entry
    I:Extracting updater binary 'META-INF/com/google/android/update-binary'
    I:Zip does not contain SELinux file_contexts file in its root.
    I:Legacy property environment not used in updater.
    Archive:  /sideload/package.zip
      inflating: app_densities.txt
    Archive:  /sideload/package.zip
      inflating: app_sizes.txt
    Archive:  /sideload/package.zip
      inflating: bkup_tail.sh
    Archive:  /sideload/package.zip
      inflating: gapps-remove.txt
    Archive:  /sideload/package.zip
      inflating: g.prop
    Archive:  /sideload/package.zip
      inflating: installer.sh
    Archive:  /sideload/package.zip
      inflating: busybox-arm
    Archive:  /sideload/package.zip
      inflating: tar-arm
    Archive:  /sideload/package.zip
      inflating: unzip-arm
    Archive:  /sideload/package.zip
      inflating: zip-arm
    libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 569 (install), pid 569 (install)
    Segmentation fault
     
    ##############################
      _____   _____   ___   ____  
     /  _  \ |  __ \ / _ \ |  _ \ 
    |  / \  || |__) | |_| || | \ \
    | |   | ||  ___/|  __/ | | | |
    |  \ /  || |    \ |__  | | | |
     \_/ \_/ |_|     \___| |_| |_|
           ___   _   ___ ___  ___ 
          / __| /_\ | _ \ _ \/ __|
         | (_ |/ _ \|  _/  _/\__ \
          \___/_/ \_\_| |_|  |___/
    ##############################
     
    Open GApps nano 9.0 - 20191213
     
    - Mounting  /vendor
     
    find: /system/system: No such file or directory
    ls: /system/system: No such file or directory
    unknown fuse request opcode 17
    df: /sideload: Function not implemented
    - Gathering device & ROM information
     
    *** Incompatible Android ROM detected ***
     
    This GApps pkg is for Android 9.0.x ONLY
    Please download the correct version for
    your ROM: 16.1.0 (SDK 27)
     
    ******* GApps Installation failed *******
     
    - Copying Log to /sideload
     
    cp: can't create '/sideload/open_gapps_log.txt': Read-only file system
    - NO changes were made to your device
     
    Installer will now exit...
     
    Error Code: 20
    cp: can't stat '': No such file or directory
    ls: /system/system: No such file or directory
    unknown fuse request opcode 17
    df: /sideload: Function not implemented
    cp: can't stat '/sideload/open_gapps_log.txt': No such file or directory
    cp: can't stat '/system/system/etc/g.prop': No such file or directory
    cp: can't stat '/system/system/default.prop': No such file or directory
    cp: can't stat '/system/system/build.prop': No such file or directory
    cp: can't stat '/vendor/vendor/build.prop': No such file or directory
    cp: can't stat '/data/local.prop': No such file or directory
    cp: can't stat '/build.prop': No such file or directory
    cp: can't stat '/system/system/addon.d/70-gapps.sh': No such file or directory
    cp: can't stat '/cache/recovery/log': No such file or directory
    /tmp/installer.sh: line 1: logcat: not found
    tar: can't open '/sideload/open_gapps_debug_logs.tar.gz': Read-only file system
    - Unmounting  /vendor
     
    Updater process ended with ERROR: 20
    I:Install took 8 second(s).
    I:Signaling child sideload process to exit.
    I:Waiting for child sideload process to exit.
    sideload_host finished
    I:[MTP] Starting MTP
    I:sending message to add 65538 '/data/media' 'Internal Storage'
    I:Message sent, add storage ID: 65538 '/data/media'
    I:Set page: 'action_complete'
    I:operation_end - status=1
    I:[MTP] created new mtpserver object
    I:[MTP] MtpServer::run fd: 20
    I:[MTP] mtppipe add storage 65538 '/data/media'
    I:[MTP] MtpStorage id: 65538 path: /data/media
</details>

Let me know if there is anything I can do to assist.

**Comment by mikegleasonjr** [comment] 2019-12-16 22:46
@kevinoid thanks it worked flawlessly

**Comment by bavay** [comment] 2019-12-31 16:01
I had the same problem. After and before every "adb sideload", I had to do a "factory reset" and "wipe Dalvik cache". It might have been a little too much, but I tried over and over again following the above instructions to no avail, only after clearing the caches it managed to boot to Lineageos (otherwise, I would end up stuck in the bootloader).

**Comment by curiousrom** [comment] 2020-01-19 07:08
>@bavay - ...I realized that I also did something else that could be the reason for the successful I nstallation: I did not install the twrp application when exiting twrp (for most of my tries, I toggled it to "install twrp app"). This could be the reason...

Some users, including me, reported fail to boot if you select install the TWRP app when asked in TWRP. That app is fluff, wants to start at boot, run in the background, collect data & is not necessary anyway because the TWRP updates are not frequent & it's easy enough to update manually. 

So go to TWRP > Settings > General and disable: Prompt to install TWRP app if not installed.

From a failed boot logcat on LineageOS 16.0 on Galaxy S5 G900M I captured for testing purposes after selecting install the TWRP app in TWRP:

--------- beginning of crash
11-20 04:02:56.647   574   574 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
11-20 04:02:56.647   574   574 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {me.twrp.twrpapp: android.permission.READ_PRECISE_PHONE_STATE, me.twrp.twrpapp: android.permission.BATTERY_STATS, me.twrp.twrpapp: android.permission.PACKAGE_USAGE_STATS}

**Comment by nezorflame** [comment] 2020-01-20 23:24
I suggest closing this then.

**Comment by mtbowler416** [comment] 2020-01-24 19:49
I'm still seeing this exact issue, on a Oneplus 3T. I have "Prompt to install TWRP" unchecked in the settings. I've tried with the latest Lineage OS 16 build, Resurrection Remix 7, and multiple versions of gapps. Both ROMs boot fine without gapps, but once I install gapps I can't get in. Doesn't matter if I boot into the OS first, then go back to TWRP and install gapps, or just install gapps right after - same result. This is incredibly frustrating!!

**Comment by nezorflame** [comment] 2020-01-24 19:54
@mtbowler416 OK, thanks for the report. A logcat of the failed boot would help.
I hope to fix that during the weekend when I have free time.

**Comment by curiousrom** [comment] 2020-01-24 20:00
> @mtbowler416 - ...Oneplus 3T. I have "Prompt to install TWRP" unchecked in the settings. I've tried with the latest Lineage OS 16 build, Resurrection Remix 7, and multiple versions of gapps. Both ROMs boot fine without gapps, but once I install gapps I can't get in...

What are the **exact** names of the LineageOS (most recent you tried) & Open GApps files that you flashed please?

As you can see [in this page](https://forum.xda-developers.com/android/software/pa-gapps-continuation-t3098071/page648) & the following in in the Open GApps XDA support thread there is a problem with Open GApps Android 9.0 Builds 2020-01-22 or newer.

The workaround @ the present is use build Open GApps 2020-01-17 or older.

Maybe you could contribute & report in that XDA thread?

>...Doesn't matter if I boot into the OS first, then go back to TWRP and install gapps…

That's not the proper way to do it.

>@nezorflame - ...I hope to fix that during the weekend when I have free time.

Thanks! Then all the builds after 2020-01-17 should be deleted ASAP & new builds should be stopped until a fix is found.

**Comment by mtbowler416** [comment] 2020-01-24 20:08
> A logcat of the failed boot would help.

Will post momentarily, just gotta run through it again...

> As you can see in this page & the following in in the Open GApps XDA support thread there is a problem with Open GApps Android 9.0 Builds 2020-01-22 or newer.

Oops... so perhaps I'm just an idiot for not noticing this. Will try with an older version in a bit and report back. My current versions are:

TWRP 3.3.1-1 (not sure if that matters, but just for completeness)
lineage-16.0-20200123-nightly-oneplus3-signed.zip
open_gapps-arm64-9.0-pico-20200124.zip (have tried pico, nano, and mini)

Appreciate the very fast responses, guys. I'm an embedded developer myself so I'm comfortable screwing around with this stuff and will help in any ways I can (although I don't particularly know much specifically about the Android kernel/ROMs/etc).

**Comment by mtbowler416** [comment] 2020-01-24 20:47
Okay, so for some reason I can't get logcat to find my device while it's booting - it just sits at "- waiting for device -". My suspicion is this has something to do with my machine/setup (2017 Macbook Pro, phone is connected via a USB-C dongle) but I could be totally off-base.

Switching back to 20200-01-17 seems to have worked like magic, I'm now in the OS. Thanks so much for the help.

**Comment by curiousrom** [comment] 2020-01-24 20:55
>@mtbowler416 - ...Switching back to 20200-01-17 seems to have worked like magic, I'm now in the OS. Thanks so much for the help.

Glad it worked for you & you are welcome.

Could you add your report in the [Open GApps XDA support thread](https://forum.xda-developers.com/android/software/pa-gapps-continuation-t3098071/page649) please?

Include the fact that you did not install the awful TWRP app.

**Comment by mtbowler416** [comment] 2020-01-24 20:59
> Could you add your report in the [Open GApps XDA support thread](https://forum.xda-developers.com/android/software/pa-gapps-continuation-t3098071/page649) please?

Will definitely do that.

**Comment by nezorflame** [comment] 2020-01-24 21:20
> 
> 
> Okay, so for some reason I can't get logcat to find my device while it's booting - it just sits at "- waiting for device -". My suspicion is this has something to do with my machine/setup (2017 Macbook Pro, phone is connected via a USB-C dongle) but I could be totally off-base.
> 
> Switching back to 20200-01-17 seems to have worked like magic, I'm now in the OS. Thanks so much for the help.

Actually no, it is so because ADB debugging is turned off for you.
You'll have to turn it on and then try to take logcat. That is, of course, if you're still up to it.

**Comment by curiousrom** [comment] 2020-01-24 21:53
>@nezorflame - Actually no, it is so because ADB debugging is turned off for you.
You'll have to turn it on and then try to take logcat. That is, of course, if you're still up to it.

It's possible to enable adb on a clean install for some devices but it's complicated.

Since my Galaxy S5 G900M running LineageOS 16.0  + Open GApps Pico 2019-09-16 & has already adb debugging setup & authorized on my PC, I can capture a continuous logcat of a reboot to System after dirty flashing open_gapps-arm-9.0-pico-20200124.zip.

Would that be useful or a waste of time?

**Comment by nezorflame** [comment] 2020-01-24 23:47
@curiousrom extra logcat won't hurt, so if you're able to do that - that'd be great.

**Comment by nezorflame** [comment] 2020-01-31 12:15
Please check on the new builds from January 31 to see if the issue is resolved.

**Comment by JarLowrey** [comment] 2020-08-18 17:35
Currently sideloading/file transfer does not work in TWRP. Instead of sideloading do this:

1. ./adb push GAPPS.zip /dev
2. TWRP menu -> Install
3. Select GAPPS.zip
4. reboot

**Comment by osm0sis** [comment] 2020-08-18 23:23
@JarLowrey that has nothing to do with Open GApps.

**Closed by osm0sis** 2020-08-18 23:23 UTC

**Comment by qxxt** [comment] 2021-11-20 12:21
No need for adb. I can evade this error just by rebooting to recovery after installing the rom. And then install the gapps.
