### ISSUE TITLE
Something wrong with Google Talkback in Oreo

### ISSUE THREAD

**Issue by nidza07** [opengapps/opengapps#569] opened 2018-01-13 15:34 UTC
Hello. In Oreo Gapps, the shortcut on the setup screen to hold 2 fingers and enable Talkback does not enable the service. On stock Android, Google Talkback is in the screen readers category of the accessibility settings, while on Android with gapps installed it is under downloaded services. It seems to me like Talkback doesn't somehow correctly get integrated into the system. Can this be checked as it is very important for blind people to independently setup their devices?

**Comment by akashgalaxy07** [comment] 2018-01-13 17:37
I second this issue.
Not only this, this is a big blocking point for us: visually impaired users who are using talkback to use their devices

**Comment by domasofan** [comment] 2018-01-13 20:34
+1

**Comment by Cleversn** [comment] 2018-01-14 14:16
I am +1 who need this.

**Comment by mrk2815** [comment] 2018-01-14 22:37
Hello. In Oreo Gapps, the shortcut on the setup screen to hold 2 fingers and enable Talkback does not enable the service. On stock Android, Google Talkback is in the screen readers category of the accessibility settings, while on Android with gapps installed it is under downloaded services. It seems to me like Talkback doesn't somehow correctly get integrated into the system. Can this be checked as it is very important for blind people to independently setup their devices?

**Comment by grnowak** [comment] 2018-01-14 23:27
As a blind user who would like to independently put lineage 15 on an older device, this is very important for me as well. Please look into this issue as soon as possible, and thanks to the folks who make lineage happen.

**Comment by ObjectInSpace** [comment] 2018-01-15 02:28
According to the version information on the opengapps download page, The Oreo GAPPS are using the N prebuilt for Talkback (5.2.1). It is absolutely imperative that this be upreved to at least 6.0 (which comes with Pixels AFAIK) as this adds support for Android O's redesigned accessibility shortcut feature. Without it, those with vision or other impairments will not be able to independently set up their devices. Cannot overstate the importance of this for PWD. Frankly, I am a little surprised that this has not been done already, and leads me to question how many other gapps in the O package are not in fact compatible with Android O until they are updated via play store.

**Comment by mrk2815** [comment] 2018-01-15 07:08
totally agree aht open gapps needs to have talkback 6.0.  as the minimum  talk back package in the open gaps repository.if you are going  to fork open gapps,   the gapps should be based  off of pixel gapps.

**Comment by JaninaSajka** [comment] 2018-01-19 15:10
This is a showstopper issue for persons who rely on Talkback. Without integrated Talkback support, LineageOS can't be termed a dropin replacement for stock Android--because Google has managed to get Talkback support integrated over many years now. It's disappointing to see no one assigned to this issue a full week after it was filed. What's the problem?

**Comment by NicholasBuse** [comment] 2018-01-25 13:29
The latest TalkBack, v6.1.0.182429506 (https://github.com/opengapps/all/commit/115877f0dca344b77bda6db9cb35312fc8b185cc), has been in the last two nightly builds ([20180124 ](https://github.com/opengapps/arm64/releases/tag/20180124)and [20180125](https://github.com/opengapps/arm64/releases/tag/20180125)).  Has the updated TalkBack had any positive effect setup experience?

**Comment by nidza07** [comment] 2018-01-25 17:02
Hi and thank you for the reply. I have noticed that Talkback 6 is now included in gapps packages and will test whether the situation is any better later today with an 8.0 rom since there are no official 8.1 gapps yet.

**Comment by nidza07** [comment] 2018-01-25 18:07
Unfortunately, the situation remains the same with Talkback 6 just like I suspected. That is, when holding 2 fingers on the screen, the message gets announced keep holding 2 fingers until you enable accessibility. After several seconds, we hear accessibility enabled but talkback is not enabled. The second thing i mentioned in the first comment is also true, Talkback being in the downloaded services category of accessibility settings instead of screen readers how it should be. I suspect Talkback is integrated differently into stock Android oreo now so it doesn't know which service to enable ie. It looks in the screen readers category but doesn't find Talkback. I hope something can be done about that.

**Comment by ObjectInSpace** [comment] 2018-01-26 00:33
What happens when you hold the volume keys down for three seconds, then release them? A dialog should appear asking to enable accessibility services. Hold both volume keys for three seconds and release them again, and TalkBack should then be enabled.

**Comment by nidza07** [comment] 2018-01-26 10:34
That should as well work, but from my testing it does not at the setup wizard. An user told me that it does with the latest talkback after setup, and on stock Android it works even on setup.

**Comment by akashgalaxy07** [comment] 2018-01-28 04:50
The included version is latest now.
if the shortcut/feature still doesn't work, then probably it's a rom specific issue.

**Comment by nidza07** [comment] 2018-01-28 13:44
I am pretty sure it is not a rom specific issue, but including the latest talkback version is simply not enough to fix that just like I suspected. There is just a different system check somewhere now. In fact, roms like Lineage 15 do not even have their setup wizard so we use the one provided by Opengapps, and that makes me suspect even more that it is not a rom issue.

**Comment by mrk2815** [comment] 2018-02-26 00:47
since lineage 15.1 has been officially  release.  The servers of lineage will have official builds of lineage 15.1  next week.Can we expect to see open gapps official  builds for 8.1 and then talkback to be working  on lineage set up wizard screen with lineage 15.1 builds and open gaps  with talkback 6.1 in  them.i I am looking forward to hearing what is going  on with the project as far as  this goes with lineage 15.1 official builds and open gapps official builds with talkback  working and accessibility.   matters for the blind  and lo vision community of custom rom users

**Comment by nidza07** [comment] 2018-05-01 12:26
Why is this still an issue? Can't somebody look at this?

**Comment by PatrickMis** [comment] 2019-04-05 15:50
For me, it is also important thing. I would like to install LineageOS with GAPPS on Oreo (8.1). Have someone information here if it still doesn't work or if it's ok?

**Comment by osm0sis** [comment] 2020-08-19 00:33
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Closed by osm0sis** 2020-08-19 00:33 UTC
