### ISSUE TITLE
ERROR64

### ISSUE THREAD

**Issue by gcjmail** [opengapps/opengapps#711] opened 2019-01-06 12:50 UTC
open_gapps-arm64-9.0-aroma-20190105.zip and open_gapps-arm64-9.0-aroma-20190106.zip
ERROR 64: Wrong architecture to set-up Open GApps' pre-bundled busybox

open_gapps-arm64-9.0-aroma-20181229.zip is ok

**Comment by darkmorpher** [comment] 2019-05-14 02:47
Duplicate of #491

**Closed** 2020-08-18 23:42 UTC
Labels: duplicate
