### ISSUE TITLE
TVSTOCK Gapps Bootloop

### ISSUE THREAD

**Issue by AryanKedare** [opengapps/opengapps#873] opened 2020-08-20 14:50 UTC
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [*] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [*] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [*] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [*] Is the issue reproducible using the latest version of your recovery?
- [] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

I Flashed latest tvstock arm gapps seems to be bootlooping the lineage-17.1 build 
link : https://konstakang.com/devices/rpi4/LineageOS17.1-ATV/ 

only 20200714 works fine   

**Reproduction Steps:**

1. [flash rom]
2. [flash gapps]
3. [reboot]

**Expected behavior:**

Build should boot normally because it boots if 20200714 is installed or without gapps

**Observed behavior:**

After flashing any newer build of tvstock build doesnt boot

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by osm0sis** [comment] 2020-08-21 08:06
@webgeek1234, any ideas?

**Comment by KonstaT** [comment] 2020-08-23 18:22
@osm0sis There hasn't been any new builds with the fix included. It should work fine once there is as I've added the missing permission myself.

**Comment by nezorflame** [comment] 2020-08-23 20:56
OK, waiting for the buildserver then, seems there weren't any APK changes for non-ARM64 archs so that's why no new builds were created.

**Comment by NicholasBuse** [comment] 2020-08-24 11:45
Historically, builds have been "forced" via: ```git commit --allow-empty -m "fresh build" && git push``` on each repo that has not had new APKs added.

**Comment by KonstaT** [comment] 2020-08-25 06:39
open_gapps-arm-10.0-tvstock-20200825 is tested and confirmed working again.

**Comment by osm0sis** [comment] 2020-08-25 07:37
Thanks!

**Comment by KonstaT** [comment] 2020-12-21 09:07
Latest tvstock gapps are broken again because of missing permissions. Using open_gapps-arm-10.0-tvstock-20201219.zip:
`
11-21 15:18:19.448   381   381 E System  : ******************************************
11-21 15:18:19.448   381   381 E System  : ************ Failure starting system services
11-21 15:18:19.448   381   381 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.tv.remote.service: android.permission.READ_P
RIVILEGED_PHONE_STATE, com.google.android.apps.mediashell: android.permission.PACKAGE_USAGE_STATS, com.google.android.apps.mediashell: android.permission.LOCAL_MAC_ADDRESS}
11-21 15:18:19.448   381   381 E System  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2970)
11-21 15:18:19.448   381   381 E System  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
11-21 15:18:19.448   381   381 E System  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3031)
11-21 15:18:19.448   381   381 E System  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21935)
11-21 15:18:19.448   381   381 E System  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
11-21 15:18:19.448   381   381 E System  :      at com.android.server.SystemServer.run(SystemServer.java:529)
11-21 15:18:19.448   381   381 E System  :      at com.android.server.SystemServer.main(SystemServer.java:356)
11-21 15:18:19.448   381   381 E System  :      at java.lang.reflect.Method.invoke(Native Method)
11-21 15:18:19.448   381   381 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-21 15:18:19.448   381   381 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
11-21 15:18:19.448   381   381 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 441ms
11-21 15:18:19.449   381   381 E Zygote  : System zygote died with exception
11-21 15:18:19.449   381   381 E Zygote  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.tv.remote.service: android.permission.READ_P
RIVILEGED_PHONE_STATE, com.google.android.apps.mediashell: android.permission.PACKAGE_USAGE_STATS, com.google.android.apps.mediashell: android.permission.LOCAL_MAC_ADDRESS}
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2970)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3031)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21935)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:529)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:356)
11-21 15:18:19.449   381   381 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-21 15:18:19.449   381   381 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
11-21 15:18:19.449   381   381 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-21 15:18:19.449   381   381 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
11-21 15:18:19.449   381   381 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.tv.remote.service: android.permission.
READ_PRIVILEGED_PHONE_STATE, com.google.android.apps.mediashell: android.permission.PACKAGE_USAGE_STATS, com.google.android.apps.mediashell: android.permission.LOCAL_MAC_ADDRESS}
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2970)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3031)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21935)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:529)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:356)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-21 15:18:19.449   381   381 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
`

**Comment by NicholasBuse** [comment] 2020-12-21 14:16
Attempted fix is in for missing permissions reported here: https://gitlab.opengapps.org/opengapps/all/-/commit/4eb6845fcaaeeb95816a05f43dc3a073de24e79c

**Comment by AleXoundOS** [comment] 2020-12-22 05:50
I confirm that the combination of lineage-17.1-20201121-UNOFFICIAL-KonstaKANG-rpi4-atv.img.zip + open_gapps-arm-10.0-tvstock-20201219.zip is unable to finish boot (I waited for 4 hours).

**Comment by KonstaT** [comment] 2020-12-22 06:49
All good with open_gapps-arm-10.0-tvstock-20201222.zip again. Thanks for the quick fix. :)

**Comment by NicholasBuse** [comment] 2020-12-22 13:53
no problem, thanks for the usable log!

**Closed by NicholasBuse** 2020-12-22 13:53 UTC
Labels: bug

**Comment by AleXoundOS** [comment] 2020-12-22 21:32
Yes, open_gapps-arm-10.0-tvstock-20201222.zip works.

**Comment by KonstaT** [comment] 2021-02-13 08:13
And again. Using open_gapps-arm-10.0-tvstock-20210213.zip:

`
01-22 10:57:46.754   399   399 E System  : ******************************************
01-22 10:57:46.755   399   399 E System  : ************ Failure starting system services
01-22 10:57:46.755   399   399 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.apps.mediashell: android.permission.READ_PRIVILEGED_PHONE_STATE}
01-22 10:57:46.755   399   399 E System  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:3055)
01-22 10:57:46.755   399   399 E System  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
01-22 10:57:46.755   399   399 E System  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3116)
01-22 10:57:46.755   399   399 E System  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21963)
01-22 10:57:46.755   399   399 E System  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
01-22 10:57:46.755   399   399 E System  :      at com.android.server.SystemServer.run(SystemServer.java:529)
01-22 10:57:46.755   399   399 E System  :      at com.android.server.SystemServer.main(SystemServer.java:356)
01-22 10:57:46.755   399   399 E System  :      at java.lang.reflect.Method.invoke(Native Method)
01-22 10:57:46.755   399   399 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-22 10:57:46.755   399   399 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
01-22 10:57:46.755   399   399 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 437ms
01-22 10:57:46.755   399   399 E Zygote  : System zygote died with exception
01-22 10:57:46.755   399   399 E Zygote  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.apps.mediashell: android.permission.READ_PRIVILEGED_PHONE_STATE}
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:3055)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3116)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21963)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:529)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:356)
01-22 10:57:46.755   399   399 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-22 10:57:46.755   399   399 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
01-22 10:57:46.755   399   399 D AndroidRuntime: Shutting down VM
--------- beginning of crash
01-22 10:57:46.756   399   399 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
01-22 10:57:46.756   399   399 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.apps.mediashell: android.permission.READ_PRIVILEGED_PHONE_STATE}
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:3055)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3116)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21963)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:529)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:356)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-22 10:57:46.756   399   399 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
`

Boots fine after adding the missing permission manually.

**Comment by Alouxndre** [comment] 2021-04-24 00:15
Hello @KonstaT 
can you explain how you change manually the permission missing ?

Thank you for your help

**Comment by KonstaT** [comment] 2021-04-24 07:30
@Alouxndre In this discussion you can find logs and links to commits that fixed the issue for couple of separate occasions.

There's nothing too special about it. Edit one the privapp-permission files and add the missing permission for the right app (you find these both from the logcat).

**Comment by Alouxndre** [comment] 2021-05-02 21:42
Hello @KonstaT ,

I tried but I failed....
I need your help a little.

What I did : I flashed with your image lineageOS 17.1 TV and install using TWRP open_gapps-arm-10.0-tvstock.
So I've got the bootloop...OK
So I read my sdcard with my computer. I mounted the rootfs.

My first issue is : I don't find the log so I can't know what are the permissions issues. Logcat can be used only on a running android if I understand well ?

Now, just for the test, I tried to find the file xml : "etc/permissions/privapp-permissions-atv.xml " It does not exist...

I'm sure I miss something and I would like to understand...

Thank you if you have a little time for a helping hand :)

**Comment by KonstaT** [comment] 2021-05-04 07:01
@Alouxndre I haven't received any other reports of issues with latest OpenGapps packages so this is probably not the right place for this discussion. Make sure that you've selected the right package for the build and that you've followed the installation instructions (you'll end up in a bootloop if you install Android TV gapps to regular tablet UI Android build or vice versa).

**Comment by AlisterAmo** [comment] 2021-05-19 02:41
Hi.
I think that open_gapps-arm-10.0-tvstock-20210518.zip is causing this issue again.
Can anybody confirm?

**Comment by FlaviusHouk** [comment] 2021-06-12 20:17
Hello.
Facing similar issue with open_gapps-arm-10.0-tvstock-20210314.zip and open_gapps-arm-10.0-tvstock-20210610.zip versions of OpenGApps and lineage-17.1-20210122-UNOFFICIAL-KonstaKANG-rpi4-atv.img. Cannot paste logs of boot for now but it looks similar to the reported (bootloop after flashing OpenGApps with TWRP).

**Comment by nrnugteren** [comment] 2021-06-23 23:34
Adding to the above:
just tested the following 2 versions and they get stuck into the same loop (as could be expected from @KonstaT 's input that newer versions are not working, but out of curiousity I tried them anyway):
open_gapps-arm-10.0-tvstock-20210619.zip
open_gapps-arm-10.0-tvstock-20210623.zip
as a TWRP install on [lineage-17.1-20210122-UNOFFICIAL-KonstaKANG-rpi4-atv.img](https://konstakang.com/devices/rpi4/LineageOS17.1-ATV),
running on a Raspberry Pi 4, 8GB (on Ethernet cable).

I would be fine with running an older version that works until bugs are fixed in upcoming releases, but was unable to find the reportedly working versions at [SourceForge.net](https://sourceforge.net/projects/opengapps/files/arm/):
open_gapps-arm-10.0-tvstock-20201121 (reported working at [KangstaKang.com](http://disq.us/p/2diztln))
open_gapps-arm-10.0-tvstock-20210206 (reported working at [KangstaKang.com](http://disq.us/p/2f34okz))
The [stable folder](https://sourceforge.net/projects/opengapps/files/arm/stable/) at SourceForge is empty.

I am about to test the next available version after 20210206 right now, from SourceForge:
[open_gapps-arm-10.0-tvstock-20210223.zip](https://sourceforge.net/projects/opengapps/files/arm/20210223/)
Will update this post with the outcome, hoping to save others some time who are also looking for a working combination.

In case that version also does not work, I'll probably run a few more tests.
But if someone can point me out a working version meanwhile that can still be found online, much appreciated! :)

**Comment by KonstaT** [comment] 2021-06-24 09:48
This isn't about finding some old version that was working but fixing the issue so you can always use the latest release.

With open_gapps-arm-10.0-tvstock-20210619.zip:

```
01-22 10:58:18.168   396   396 E System  : ******************************************
01-22 10:58:18.169   396   396 E System  : ************ Failure starting system services
01-22 10:58:18.169   396   396 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.tv.remote.service: android.permission.MEDIA_CONTENT_CONTROL}
01-22 10:58:18.169   396   396 E System  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:3055)
01-22 10:58:18.169   396   396 E System  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
01-22 10:58:18.169   396   396 E System  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3116)
01-22 10:58:18.169   396   396 E System  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21963)
01-22 10:58:18.169   396   396 E System  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
01-22 10:58:18.169   396   396 E System  :      at com.android.server.SystemServer.run(SystemServer.java:529)
01-22 10:58:18.169   396   396 E System  :      at com.android.server.SystemServer.main(SystemServer.java:356)
01-22 10:58:18.169   396   396 E System  :      at java.lang.reflect.Method.invoke(Native Method)
01-22 10:58:18.169   396   396 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-22 10:58:18.169   396   396 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
01-22 10:58:18.169   396   396 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 467ms
01-22 10:58:18.169   396   396 E Zygote  : System zygote died with exception
01-22 10:58:18.169   396   396 E Zygote  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.tv.remote.service: android.permission.MEDIA_CONTENT_CONTROL}
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:3055)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3116)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21963)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:2037)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:529)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:356)
01-22 10:58:18.169   396   396 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-22 10:58:18.169   396   396 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
01-22 10:58:18.169   396   396 D AndroidRuntime: Shutting down VM
```

Boots fine after adding android.permission.MEDIA_CONTENT_CONTROL for com.google.android.tv.remote.service.

**Comment by nrnugteren** [comment] 2021-06-24 10:08
Ok, now I'm enthusiastic to give that one a shot, after I tested 20210428.

Adding that part makes sense, but truth to be told it sounds like Chinese to me at this point haha - haven't added permissions on anything Android before.
I'll do some research on that to figure it out, shouldn't be rocket science I guess.

Thanks once more!

**Comment by NicholasBuse** [comment] 2021-06-24 13:27
Fix for adding android.permission.MEDIA_CONTENT_CONTROL for com.google.android.tv.remote.service here: https://gitlab.opengapps.org/opengapps/all/-/commit/3cc21692d39e5299fe09835de04086516a794d3f

**Comment by nezorflame** [comment] 2021-10-11 17:40
I can build you one to test with these changes now, or you can wait for the next official release.

**Comment by KonstaT** [comment] 2021-10-11 17:56
@Letniq
That permissions file gets extracted to /system/etc/permissions/privapp-permissions-atv.xml (I don't even know where it's inside the gapps zip). You can mount the Pi sdcard/USB image on your Linux machine and edit the file.

@nezorflame
As far as I'm concerned the Android 10 tvstock situation is resolved as it will be fixed with the next build. But it would be nice to have tvstock package for Android 11 as currently there isn't any (official releases only for nano & pico and the old test package from 20210110 was just recently removed from sourceforge).

**Comment by dwemerlord667** [comment] 2021-10-13 06:11
Ok then thanks for replying so fast.

**Comment by KonstaT** [comment] 2021-10-13 08:38
They are up. Thank you @mfonville

Tested open_gapps-arm-11.0-tvstock-20211013.zip and all fine apart from Google's Android TV Remote Control app no longer works (still worked with open_gapps-arm-11.0-tvstock-20210110-TEST.zip). Though I'm not sure if it's even supposed to work with latest Google services as they also removed it from the Play Store a while back (was https://play.google.com/store/apps/details?id=com.google.android.tv.remote, apk still available at https://www.apkmirror.com/apk/google-inc/remote-control/remote-control-1-1-0-3876957-release/).

**Comment by KonstaT** [comment] 2022-04-29 06:31
With open_gapps-arm64-11.0-tvstock-20220426.zip:

```
01-21 07:46:09.375  1068  1068 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
01-21 07:46:09.375  1068  1068 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.gms (/system/priv-app/PrebuiltGmsCorePano): android.permission.MEDIA_CONTENT_CONTROL}
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:4703)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.access$500(PermissionManagerService.java:178)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:4786)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21692)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.server.SystemServer.startOtherServices(SystemServer.java:2210)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:601)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:417)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-21 07:46:09.375  1068  1068 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
01-21 07:46:09.731     0     0 I init    : Service 'zygote' (pid 1005) received signal 9
```

Boots after adding android.permission.MEDIA_CONTENT_CONTROL for com.google.android.gms.

**Comment by nezorflame** [comment] 2022-04-29 06:54
Strange, permission script should've caught that.
Thanks for the report, I'll fix this today and remove the build.

**Comment by NicholasBuse** [comment] 2022-05-02 14:46
Added permission in: https://gitlab.opengapps.org/opengapps/all/-/commit/97d1466eeea28f87d126b63dba864cd4713db337 while we continue to debug the permission script integration
