### ISSUE TITLE
Give a better error message when the user forgets to reboot

### ISSUE THREAD

**Issue by josephcsible** [opengapps/opengapps#768] opened 2019-09-06 01:57 UTC
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**

When a user forgets to reboot between installing the ROM and OpenGApps on an A/B device, the error message is unhelpful and wrong.

**Reproduction Steps:**

1. On an A/B device, flash a new ROM (such as LineageOS).
2. Without rebooting, attempt to flash OpenGApps.

**Expected behavior:**

I expect an error message that says something to the effect of "since you have an A/B device, you need to reboot in between flashing your ROM and flashing OpenGApps"

**Observed behavior:**

I get an error message that arm64 is the wrong architecture for my device, and that I need the arm build instead (which is not true).

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

**Comment by darkmorpher** [comment] 2019-09-07 22:02
Duplicate of #491 #711

reports: TeamWin/Team-Win-Recovery-Project/issues/1070

**Comment by josephcsible** [comment] 2019-09-07 22:31
Those just look like other random posts where the symptom was the wrong architecture message, rather than actual duplicates of the same underlying cause. In particular, most of them aren't even from A/B devices.

**Comment by osm0sis** [comment] 2020-08-18 23:19
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Closed by osm0sis** 2020-08-18 23:19 UTC
