### ISSUE TITLE
Please provide stock DialerGoogle

### ISSUE THREAD

**Issue by vincent-t** [opengapps/opengapps#248] opened 2016-02-01 12:18 UTC
Why is the stock DialerGoogle not included, so it's possible to remove the aosp dialer.

**Comment by mfonville** [comment] 2016-02-01 12:25
duplicate of #197 
please don't open directly new issues without checking xda and/or existing list of issues.

**Closed by mfonville** 2016-02-01 12:25 UTC

**Comment by vincent-t** [comment] 2016-02-01 12:41
@mfonville Sorry my fault, I'm blind! :-1:
