### ISSUE TITLE
Google Camera

### ISSUE THREAD

**Issue by wodim** [opengapps/opengapps#208] opened 2015-12-29 13:11 UTC
Any reason to include the new Google Camera? It crashes in most if not all phones because they don't support and they will never support the new camera API; in fact the only phones that support it by now are the new Nexus devices.

**Comment by mfonville** [comment] 2016-01-04 22:47
Could you further detail the list for me which Nexus devices *do* support the new camera API, then I can look at how to distinguish them and check out how I can improve the installer behaviour.

**Comment by wodim** [comment] 2016-01-04 22:49
I don't know, sorry. I've been told only the most modern Nexus devices support that API.

The actual problem here is that Google Camera crashes for 99% of the users.

**Comment by legendtang** [comment] 2016-01-06 14:25
https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera&hl=en
> Requirements
• Google Camera works on Nexus phones running Android 6.0 and above
• SmartBurst is only available on the Nexus 6P
• Slow motion video is only available on the Nexus 5X and 6P
• Photo Sphere and Panorama require a gyro sensor
• Photo Sphere, Panorama, and Lens Blur require at least 1 gigabyte of memory

According to my testing, my non-Nexus devices running CM / AOSP Android 6.0 would only install v2.5 one from Play Store directly, thus in my presumption, only vanilla Android 6.0 compiled by Google (Nexus 4+, Google Play Editions) supports the new Google Camera. (Google Sucks!)

BTW, I prefer the former option.

**Comment by jrior001** [comment] 2016-01-16 17:18
I'd like to add to this the main x86 device w/a camera that is getting Aosp/CM/other builds (zenfone 2) can't use this new camera either. The 3.0+ Google Cam requires an api2 camera Hal and pretty much only Nexus w/official M release is shipping an api2 capable camera hal.

**Comment by eugenesan** [comment] 2016-01-19 16:35
I can confirm that Google camera from 6.0 crashes (in video mode) on HTC-Pyramid, while it's older version from Android 5.1.1 is working fine.

Maybe for non-nexus devices, an older variant can be added alongside the new one so user could select the variant he wants to install?

Is there anything on target system that can indicate availability of API2?

**Comment by m-p-3** [comment] 2016-01-20 13:37
Same issue with my LG G3 (d852) on CM13 nightly 20160118. Removing Google Camera from system/app and installing from the Play Store will download version 2.5.052.

This one won't freeze when switching to video mode. Pictures taken with HDR mode on will often turns out fully black, but that seems more like a CM13-specific issue.

**Comment by legendtang** [comment] 2016-01-20 13:47
A good alternative is to use newly introduced Snap Camera by CyanogenMod 13, which is powerful enough.

* http://www.xda-developers.com/xda-external-link/cyanogenmod-13-nightlies-reportedly-comes-with-snap-camera-app/

To use this app with openapps, you need to create an `gapps-config.txt` where your opengapps zip located with these following lines:

````
CameraGoogle
CameraStock
````

**Comment by mfonville** [comment] 2016-01-27 21:54
This is now fixed. The installer script automatically installs the older Google Camera on non-Nexus and Android One devices.

**Closed** 2016-01-27 21:53 UTC
Labels: enhancement, in progress

**Comment by Shished** [comment] 2017-01-10 19:48
App will not crash is device supports Camera2 API. OpenGapps installer should check build.prop for the corresponding line 
`persist.camera.HAL3.enabled=1`
and if it presents install camera version 3, otherwise install version 2.

**Comment by mfonville** [comment] 2017-01-10 21:12
@Shished it already does that now for a year: https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L1322-L1324
