### ISSUE TITLE
Installation fails on AB partitioned device with error 70

### ISSUE THREAD

**Issue by HonoluluHenk** [opengapps/opengapps#789] opened 2020-01-02 01:18 UTC
**Checklist**

- [X] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps installation fails:*
- [X] Is the issue reproducible using the latest version of your recovery?
- [X] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**
Open GApps installation fails with error 70 (Insufficient space on system partition)

Relevant snippet of open_gapps_log.txt (please note the strange text-values for sizes!)
```
         Total System Size (KB) | Filesystem
         Used System Space (KB) | 1K-blocks
        Current Free Space (KB) | Used
```

**Reproduction Steps:**
Latest TWRP already installed on both partitions A and B (currently: version 3.3.1-0.)

1. Activate partition A
2. Install custom ROM (e.g.: Resurrection Remix. This typically gets installed on the other partition, i.e.: B)
3. Activate partition B
4. Reboot into TWRP
5. Install OpenGapps (i.e.: on partition B)

**Expected behavior:**
OpenGapps installs without error.

**Observed behavior:**
Install fails with error 70

**In-depth explanation**

Relevant section of open_gapps_log.txt:
```
                    Device Name | jasmine_sprout
                   Device Model | Mi A2
                    Device Type | phone
                     Device CPU | arm64-v8a,armeabi-v7a,armeabi
          Device A/B-partitions | true
             Installer Platform | arm
                   ROM Platform | arm64
```

My Device is a A/B partioned device. This gets detected correctly and installer.sh sets SYSTEM_MOUNT to /system.
But: on my device, /system_root is relevant instead of /system.
(FYI: /system exists but is empty and not mentioned in /etc/fstab)
This somehow leads to `df=$(df -k $SYSTEM | tail -n 1);` to /only/ return this line:
`Filesystem     1K-blocks      Used Available Use% Mounted on`

Interestingly, after starting the custom ROM and then rebooting into TWRP, df -k /system works as expected!

**Comment by HonoluluHenk** [comment] 2020-01-02 01:19
**Workaround (for all those that might arrive via google):**
If you find these strange values for system sizes mentioned above (Total/Used/Current System Size):
Open your downloaded open_gapps*.zip file, and edit installer.sh as such:
Replace the first occurrence of 
```
  device_abpartition=true
  SYSTEM_MOUNT=/system
```
with:
```
  device_abpartition=true
  SYSTEM_MOUNT=/system/root
```

Then re-pack the zipfile and retry.

Good luck!

**Comment by nezorflame** [comment] 2020-01-12 13:33
Hi @HonoluluHenk! Thanks for reporting this.
Could you also mention which build of OpenGApps did you use to check this, since the stable builds and the beta builds for Android 10 have different mounting scripts?

**Comment by HonoluluHenk** [comment] 2020-01-12 20:52
latest OpenGapps 9

**Comment by HonoluluHenk** [comment] 2020-01-12 20:54
... from https://opengapps.org/ as of 27.12.2019. Unfortunately I deleted the files and do not know the exact version :(

**Comment by nezorflame** [comment] 2020-01-20 20:58
@HonoluluHenk this should've worked since 16 January release. Were you able to check it?

**Comment by nezorflame** [comment] 2020-01-20 20:59
This will work once we merge the Q PR: https://github.com/opengapps/opengapps/pull/773

**Comment by Suavesito-Olimpiada** [comment] 2020-01-26 01:56
Hi, I downloaded OpenGapps Pico ARM for Android 9.0 from 24/01/2020 (latest), tried installing in A/B phone and was unable to install them. I checked this issue and this exact issue (error 70), with this text in open_gapps_log.txt appear

> Relevant snippet of open_gapps_log.txt (please note the strange text-values for sizes!)
> 
> ```
>          Total System Size (KB) | Filesystem
>          Used System Space (KB) | 1K-blocks
>         Current Free Space (KB) | Used
> ```

I tried to do what s done [here](https://github.com/opengapps/opengapps/issues/789#issuecomment-570099731) but didn't find the variable.

Do you have suggestions in how to fix it?

**Comment by nezorflame** [comment] 2020-01-26 14:39
Hi @Suavesito-Olimpiada.
Have you by any chance had updated the TWRP on your device lately? Their devs have made a change to how things are handled there so now our mounting scripts are failing in that case.
There's a possible fix in the works (https://github.com/opengapps/opengapps/pull/797), I'll update this thread once it's merged.

**Comment by nezorflame** [comment] 2020-01-31 12:15
Please test the new builds from January 31 to see if the issue is resolved.

**Closed** 2020-08-18 23:13 UTC
