### ISSUE TITLE
Wrong arhitecture ?

### ISSUE THREAD

**Issue by blackPantherOS** [opengapps/opengapps#650] opened 2018-07-31 10:00 UTC
Hi all opengapps package installation failed with "Error 64: Wrong arhitecture to set-up... " error message (you can look on URL [https://ibb.co/mBh918](url)). 

Few days ago ONLY opengapps-**FULL** package worked fine without error and installation successful. Now does not work. I use TWRP 3.2.2-1 Phone is a Samsung Galaxy S4 i9505 

Tested with OpenGapps ARM - 8.1 pico, nano, micro, mini aroma  - Installation stopped with error

**Comment by Alvarord** [comment] 2018-08-20 19:57
Hello, 

I had a similar problem installing lineageOS 15.1 I tested with the [MindTheGapps]( https://github.com/MindTheGapps ) and it worked.

I read [this](https://lineageos.org/Changelog-19/):

> Currently, the only GApps compatible with this new addon.d system (deemed addon.d-v2) is MindTheGApps. OpenGApps addon.d script in its current form is too complicated for addon.d-v2 to handle (as A/B was never meant to handle this sort of thing), though we’ve reached out, and alerted them what needs to be done. If you wish to make your addon.d mod v2 compliant, please look [here](https://github.com/MindTheGapps/vendor_gapps/blob/master/addond_tail) for an example addon.d script, and [here](https://github.com/MindTheGapps/vendor_gapps/commit/74859c6634b8d8df7bc674847513a9686e0e67e7) for the flag to make it compatible. Any third party mods not flagged with the above will be ignored by addon.d-v2, and not backed up as they are incompatible.

I would prefer opengapps with pico variant working. could it be possible? Could the issue be related with this?

**Comment by coderfox** [comment] 2019-01-06 06:50
Same on Android Pie, OnePlus 5, TWRP by codeworkx.

**Comment by speakxj7** [comment] 2019-04-29 17:35
i found if installing OS from bare nothingness, another reboot to recovery may be required after os install, before installing gapps. seems the detection of OS is a bit sticky. (so instead of doing a series of zips in one-shot)

**Comment by darkmorpher** [comment] 2019-05-14 02:47
Duplicate of #491

**Comment by lbdroid** [comment] 2019-06-10 14:20
Its usually just because opengapps can't find the unzip command on your /system partition. I believe it looks in /system/xbin/ while many installs have it at /system/bin/

Just copy the file over and try again.

**Comment by osm0sis** [comment] 2020-08-19 00:12
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Closed by osm0sis** 2020-08-19 00:12 UTC
