### ISSUE TITLE
Google Dialer does not replace the AOSP dialer

### ISSUE THREAD

**Issue by shashankshirke285** [opengapps/opengapps#281] opened 2016-03-17 13:59 UTC
GApps stock package for 6.0 shows the Google Dialer in the list of apps that replace the AOSP apps but it is striked off in the list. The Google dialer is not installed and instead AOSP stays even after installing the Stock GApps package. Any specific reason for striking of the Dialer app?

**Comment by mfonville** [comment] 2016-03-17 14:07
Duplicate of #197 
We are still in the process of packaging it in reliable way without breaking 99% of the phones.

**Closed by mfonville** 2016-03-17 14:07 UTC

**Comment by shashankshirke285** [comment] 2016-03-17 14:09
Is there a way to have it installed and replace the AOSP version now? I tested the Google phone app on my device and it seems to work fine.

**Comment by mfonville** [comment] 2016-03-17 14:14
Remove the AOSP version using e.g. https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#universal-application-removals

**Comment by shashankshirke285** [comment] 2016-03-17 15:39
OK thanks! Any ETA on when the Google dialer would be included into the stock package?

**Comment by mfonville** [comment] 2016-03-17 15:55
No, no ETA yet, working on some other issues at the moment.
