### ISSUE TITLE
20 April 2019 ARM 64 9.0 Aroma error code 64

### ISSUE THREAD

**Issue by gwiqu** [opengapps/opengapps#735] opened 2019-04-23 02:24 UTC
there is an issue with the aroma installer, it gives me code 64 which is an incompatible device architecture, even though im on the correct architecture, the 14 April 2019 ARM 64 9.0 Aroma installer does not have this issue

**Comment by darkmorpher** [comment] 2019-05-14 02:42
Duplicate of #491

**Closed** 2020-08-18 23:34 UTC
