### ISSUE TITLE
gapps language installation problem

### ISSUE THREAD

**Issue by julolosvalles26** [opengapps/opengapps#744] opened 2019-06-02 02:08 UTC
I am using lineage os 16 and use gapps aroma 64 bits the problem is that some apps like chrome, fit, youtube maps and almost all in general are in English even though my language is Spanish I can not install almost any app except play store and the basic things and the rest download from play store once the system is installed but I would like to flase the apps in my language has not been solved but it is going to get worse but apps are wrong the language I have also seen that in older android this is the problem although it affects something less thank you forgiveness if I write badly I am Spanish this is difficult

**Comment by tOz-666** [comment] 2019-06-18 11:20
This also happens on stock gapps for 9.0 arm64.
Temporary fix is to uninstall (using root) the system app with an appropiate tool, and then installing the same app from Play Store (gets converted to user app).

Also if the app gets updated via playstore (because there is a newer version available) it also gets the translated version in the process. This happened to me with Google Maps, but gapps chrome version right now is 75.x.x.x and Play Store (for my device at least) still has 74.x.x.x so the update never happens.

The former fix is doable to translate the app though, but it's not ideal and has to be done on every ROM reinstall.

**Comment by yurikoles** [comment] 2019-06-20 17:42
Duplicate of #675. @julolosvalles26 please close this.

**Comment by julolosvalles26** [comment] 2019-06-20 17:49
yes i know but they still do not solve the language problem and it's going to get worse instead of bothering with duplicate messages you could work on the problem i wonder is not it or is it easier to close notice in duplicate

**Comment by julolosvalles26** [comment] 2019-06-20 17:52
I'm looking for the others to close them and I do not see them I do not know how to look for them or they are no longer

**Comment by yurikoles** [comment] 2019-06-20 18:52
Why do you think that your issue is so special? Instead of opening new issue you too may just work on the problem.

**Comment by julolosvalles26** [comment] 2019-06-20 19:02
is special because there are more people that affect you and is in more versions of android and it will not be better anymore apps have the flaw they will not fix it will repair phones install roms and this kind of things do not create apps because this problem occurs but it prevents me from installing a lot of apps from the installer aroma because afterwards the language is wrong

**Comment by julolosvalles26** [comment] 2019-06-20 19:07
The fact is that before this did not happen in previous versions because now? they should not improve over time

**Comment by yurikoles** [comment] 2019-06-20 19:17
@julolosvalles26 I suggest you to ban yourself on GitHub since you completely don't understand how Free Software works. You are not special and no one owe you anything. Instead of filling duplicate issue just solve it or stop using it, no one force you to use it.

**Comment by julolosvalles26** [comment] 2019-06-20 19:42
ok it's ok you're right I'm just a user who installs roms and aregla moviles I'm not a programmer not repairing that but I expected that you do and have been champions for months but it's true what you say do not worry I will not use it anymore try to solve it please or it is impossible thank you and goodbye

**Closed** 2020-08-18 23:29 UTC
