### ISSUE TITLE
Open GApps for Stock - merge with @RapperSkull's GApps for Stock

### ISSUE THREAD

**Issue by rapperskull** [opengapps/opengapps#26] opened 2015-06-23 13:01 UTC
When TKruzze decided to leave the scene for a while, a lot of GApps packages rose, all very similar to the original PA GApps. Since I'm contributing (a little bit) to the Open GApps project, I thought that would be nice to merge two GApps packages with two different aims but very similar code.
To merge the two projects there are some steps to perform:
1. Rewrite the makefile to make it more dynamic: replace the single parameter with multiple parameters specifying the GApps type (normal, for stock, or all), the api version (19, 21, 22 or all), the packages to build (stock, full, mini, micro, nano, pico, aroma and all) and the architectures (arm, arm64, x86, x86_64 or all).
2. Introduce the new "for stock" modifier, similar to the API version one (a lot of changes happen when building for KitKat).
3. Merge some more removals (found in some ROMs that also includes GApps).

Some of the changes that should be made when building "for stock" consist in:
1. Remove the already installed GApps check, or better allow the installation only if GApps are already installed but no g.prop file is found or it's Open GApps
2. Remove the check for potential ROM conflicts
3. Always install WebViewGoogle by default
4. Remove /system/lib/libchrome.*.so when installing Chrome

**Comment by mfonville** [comment] 2015-06-23 13:54
Great idea to merge these two. Actually I recently checked out your GApps for Stock XDA page, and was already wondering if somehow integrating them would be possible.

For the makefile, it took me quite some magic work to make the current looping-mechanism working correclty, so adding an extra loop to it will be challening (but fun).
One small, possibble, issue though, is that currently we 'recycle' the 'build' area for building all the variants. At the start this was necessary, to produce the sizes.prop, but since that file is now not in existance anymore (yay!) it will be possible to make a seperate build-area for each variant. It will just take a lot more disk-space when producing all the packages.

About the default installation of WebViewGoogle, it is of course already part of the default 'stock' package, we just have to limit it to the 5.1 package though. I looked at the CM-sources, and no-one is backporting that alternative webview-patch to 5.0, we can only make (within a small month, when all ROM spins have this patch) installing the Google Webview by default on 5.1+.

I expect you to be able to do the groundwork for the merger, though best would not to commit it directly to the master branch until it is reviewed. Because I would have to update my buildbot scripts afterwards, and have to make sure my server has enough disk space.

**Comment by rapperskull** [comment] 2015-06-24 10:10
I'll write the code in a separate branch, will you take a look at the makefile? I'm completely inexperienced in this field.
As for as the WebView, it can be installed on 5.0 too on stock ROMs. We'll have to further separate the two packages.

**Comment by mfonville** [comment] 2015-06-24 10:34
I will review your code of course. I will see if I can tweak the makefile.
We also might need a better keyword than 'for stock' because it contains a space (not nice) and also contains 'stock' like the existing 'stock' package. Would something like 'fornexus' or so be appropiate? What are your thoughts on that?
Is there a reliable way that we can identify which rom is really 'Stock' as intended by your package?

**Comment by mfonville** [comment] 2015-06-24 11:17
Update: the groundwork for revising the makefile and all related script parts is almost done. It works, I am just cleaning up some things, so I will still commit it today :D

**Comment by mfonville** [comment] 2015-06-24 11:58
Shit, I thought only the sizes.prop was problematic, but now, when almost everything finished, I remember that makegappsremovetxt also relies on having a full-set of paths available, to be able to delete them :/
I have to find a fix for this issue

**Comment by rapperskull** [comment] 2015-06-24 13:18
Maybe we can keep the same build path: the only thing that changes is the update-binary file and we could use different names to distinguish between them. As for as the name, I would like to keep "Open GApps for Stock", because my previous package worked fine on some ROMs that came with already installed GApps (thanks to some more removals) and not only Nexus devices, but the keyword can be easily changed to "fornexus", no problem.
Regarding the Stock check, it's not really easy, first of all because there's no ROM name like CM or others, but also because of the compatibility with other custom ROMs. I think it's up to the users decide to flash or not to flash the package. We can also include a list of known problematic ROMs if users will complain and simply adding more removals is not of help. Obviously we'll have to include a big warning near the download link to warn the users that compatibility in not guaranteed.

**Comment by mfonville** [comment] 2015-06-24 15:11
I already incorporated the changes. My script now just tries to 'steal' the gapps-remove.txt from the 'stock' build, and refuses to build if there is no 'stock'.
I like the changes, because it makes things more easy and structured, I just have to find a better fix for this gapps-remove.txt, but I think I will do that when revising some of the inc.buildtarget.sh anyhow, when multi-DPI will be incorporated. (I have some ideas, just lack of time to implement them till now).

So, we will settle on the 'fornexus' keyword then.

About checking for stock, pity there is not a good reliable indicator. But maybe we can check the build.prop for ro.build.host and see if it ends on corp.google.com? (Not sure if that applies to all nexus builds?)

**Comment by rapperskull** [comment] 2015-06-24 18:24
Yes, I think the ro.build.host parameter is good enough for now. We'll add more checks if and when users will complain (and provide logs).
As for as the changes to inc.updatebinary.sh I'm currently stuck because I don't know how the build of the "fornexus" variant will be called, for now I'll write 'if [ "$gapps_variant" = "fornexus" ] then ....', then we'll change the variable name according to your changes to the Makefile.

**Closed** 2015-06-26 11:17 UTC
Labels: enhancement
