### ISSUE TITLE
Keep the stock dialer by default, instead of as configuration due to emergency calls not functioning properly sometimes.

### ISSUE THREAD

**Issue by Senexis** [opengapps/opengapps#672] opened 2018-10-10 20:48 UTC
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [X] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [X] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [X] Is the issue reproducible using the latest version of your recovery?
- [X] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [X] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [X] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [X] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [X] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

I have recently had an issue while needing to dial 911 (thankfully I could still talk to and hear the 911 operative) due to the stock dialer being removed and I am enraged to find out that this is default behavior for Stock+ packages without any mention of the risks whatsoever. Sure, you've added an optional keyword for it in the config (which I doubt everybody is even aware of), but keeping the stock dialer should really be the default operation, not an optional one.

Now I know that you can't expect to ignore every app install that may cause issues. There's going to be issues (be it in relatively meaningless logs or some force closes), but if it could potentially cause a user to not be able to use the emergency call functionality, this should not be put in the same category of "well, your fault".

**I know and acknowledge that I am responsible for the working of all my device's features** when I flash something, anything, onto my device, but please protect the less-eager-to-learn-everything-before-flashing user (me included) from making a potentially life-threatening mistake by not knowing this is a potential issue.

The emergency dialer is not something the regular hobbyist can easily fully test depending on the country. Calling 911 without a genuine reason or as a pre-announced test is illegal. I know that in the Netherlands you have to go through an excessive talk with multiple governmental bodies to request such a test call. **Meanwhile, most people aren't even going to think about testing this. They'll only find out when they are in a situation in which they need to dial 911.**

Please consider making keeping the stock dialer the default instead of optional, and using something like an explicit `-StockDialer` option with preferably a very clear written warning accompanying this. I don't feel like the mild inconvenience of having to hide the default "Phone" app outweighs the potential risk of not being able to reach emergency services when you need them the most.

**Comment by jamuir** [comment] 2018-10-11 01:06
> The emergency dialer is not something the regular hobbyist can easily fully test depending on the country. 

There is a way to test it by setting a system property:

https://github.com/opengapps/opengapps/issues/618#issuecomment-386046309

**Comment by Senexis** [comment] 2018-10-11 05:18
That is actually really helpful. Thanks a bunch. 🙂

It doesn't, however, really solve my issue with this whole deal, and I still think this should be considered.

**Comment by NicholasBuse** [comment] 2018-11-26 14:43
@curiousrom , Stop being a jerk. I can copy and paste the same comments everywhere (https://github.com/opengapps/opengapps/issues/618, https://github.com/opengapps/opengapps/issues/672) to get people attention too. It is not helpful.

Here is how you can be helpful: https://github.com/opengapps/opengapps/fork

**Comment by Senexis** [comment] 2018-11-26 14:56
Why did you close this issue? I would still like this issue to be resolved (or at least; denied with explanation). I would appreciate it if you could at least comment on this issue in any way. I am still actively following this issue, and as far as I can tell, it hasn't been resolved in the way that I mentioned so I'm left to wonder why this was closed.

Feel free to disagree with me, but I don't think closing the issue after it gets the wrong attention by a cross-spam poster is the way to go here. I am still looking for an answer or solution to this problem.

**Comment by curiousrom** [comment] 2018-11-26 16:31
@NicholasBuse - I was expecting that kind of kneejerk reaction but the **life threatening** emergency call problem needs **urgent** attention & it has been festering for months.

I am just trying to get the Open GApps team to put that bug way up on the priority list.

I understand that all the work is done by unpaid volunteer & I am grateful for it.

If the team can't find a solution to fix the script that removes the stock dialer by default in the Open GApps Packages Mini, Full, Stock or Super then get some external help.

Ask for help in XDA, the LineageOS subreddit, stackoverflow, stackexchange, etc.

I was also expecting answers like your "Here is how you can be helpful: https://github.com/opengapps/opengapps/fork " but I am not a developer otherwise I would try to fix it instead of posting about it.

You can check my posting history on XDA, I am a user support kind of guy & proud of my contributions to the community: https://forum.xda-developers.com/member.php?u=4122877

Your "...paste the same comments everywhere" comment is overboard as I posted in exactly **2** threads and both about the broken emergency calls issue and the comments are different.

Misleading personal attacks or closing a thread instead of trying to find a solution is not constructive IMO.

@DavidBerdik got the point I am trying to make in his post here https://github.com/opengapps/opengapps/issues/618#issuecomment-441665284

> ...I think I speak for everyone here when I say that the OpenGApps project is a wonderful piece of work and is essential to the custom ROM community, but the fact that this issue has not been given more attention is really concerning...

**Comment by SpasilliumNexus** [comment] 2018-11-26 20:09
Done. Now this can be closed once and for all.

**Comment by curiousrom** [comment] 2018-11-26 20:54
>           Done. Now this can be closed once and for all.

Wow thank you @SpasilliumNexus!

Can we have some time to download once the packages are online, test & report before the issue is closed?

**Comment by SpasilliumNexus** [comment] 2018-11-26 20:57
Builds for Pie (ARM/ARM64, Mini only): https://forum.xda-developers.com/showpost.php?p=78267478&postcount=5765

**Comment by DavidBerdik** [comment] 2018-11-26 21:17
Question: Is there a way I can apply this fix to my OpenGApps installation? My ROM releases regular updates so that would not be an issue if it were a requirement.

@curiousrom - Looks like I've been wiped from history.

**Comment by curiousrom** [comment] 2018-11-28 10:34
I'm sorry to report that I ran a test install of open_gapps-arm-9.0-stock-20181128.zip using gapps-config.txt with test enabled in the same root of ext. sdcard & looking in the open_gapps_log.txt which I attached to this post:

**Remove Stock/AOSP Dialer | true[default]**
Ignore Google Dialer | false[DialerGoogle]
Remove |                dialerstock
Install |               dialergoogle
***

[open_gapps_log_Stock_Test_2018-11-28.txt](https://github.com/opengapps/opengapps/files/2623970/open_gapps_log_Stock_Test_2018-11-28.txt)
[open_gapps_debug_logs_Stock_Test_2018-11-28.tar.gz](https://github.com/opengapps/opengapps/files/2623972/open_gapps_debug_logs_Stock_Test_2018-11-28.tar.gz)
[gapps-config.txt](https://github.com/opengapps/opengapps/files/2623973/gapps-config.txt)

**Comment by SpasilliumNexus** [comment] 2018-11-28 11:54
Copying the exact reply I made in the XDA thread, since you've done that too...

Look at the commit made: [url]https://github.com/opengapps/opengapps/commit/0392c9cb249ce0584e5144143f6a9500941bed72[/url]

Look at this specific line: [url]https://github.com/opengapps/opengapps/commit/0392c9cb249ce0584e5144143f6a9500941bed72#diff-4b4d756dd3b2a232970b47588e486eddR388[/url]

That one line prevents Phone from being removed. Again, I did this on a LIVE install, with no TEST keyword, and it DOES NOT remove it. It removes other entries found (FineOSDialer and OPInCallUI) ONLY.

Edit: Even looking in your gapps-remove_revised.txt inside your open_gapps_debug_logs_Stock_Test_2018-11-28.tar.gz shows that priv-app/Dialer is not in the removal list...

**Comment by curiousrom** [comment] 2018-11-28 16:33
Sorry if the package installation Test simulation feature does not reflect you fix.

I had no way to know that.

Anyway thanks for your time & fixing the failed emergency call issue!

**Comment by curiousrom** [comment] 2018-12-02 11:57
>           Even though the stock Dialer needs installed to resolve the 911 bug, does it have to be enabled? I would like to disable the stocker Dialer so that I do not have two Phone apps in my drawer...

_"...does it have to be enabled?"_ - **YES!** Because the default stock Dialer is the one being used for emergency calls by default in many AOSP custom firmwares including LineageOS.

Why not just make the Google Dialer the default, create a shortcut to it on the Desktop & disregard the stock Phone in the app drawer?

There are some launchers that can hide apps if it's really bothering you.

**Comment by DavidBerdik** [comment] 2018-12-02 17:05
In that case, I'll just ignore it. I use the default Pixel launcher and I like it enough to compromise having the app there. The shortcut setup you described is actually what I am currently using. I'll just leave it that way.

**Comment by SpasilliumNexus** [comment] 2018-12-10 18:13
Testing... [Scripts: DialerStock > OtherDialerStock, Add keyword AOSPDialer](https://github.com/SpasilliumNexus/opengapps/commit/d14ed7fbd66f1ce3e4adec662bf9638cceb596b1)

**Comment by yurikoles** [comment] 2018-12-10 18:23
Is there an option to keep old behavior? I don't have emergency issue and don't want to have two dialers installed.

**Comment by viggy96** [comment] 2018-12-20 20:15
> In that case, I'll just ignore it. I use the default Pixel launcher and I like it enough to compromise having the app there. The shortcut setup you described is actually what I am currently using. I'll just leave it that way.

Try the Lawnchair lawncher. It has an identical look to the Pixel launcher, but is much more customisable. The alpha version is the one you want, and there are continuous integration builds of it available on APKMirror. That way you can hide apps, like the stock dialer, and have many more customisation features.

**Comment by DavidBerdik** [comment] 2018-12-20 21:00
@viggy96 It looks pretty cool! Thanks! I will check it out!

**Comment by osm0sis** [comment] 2020-09-22 20:51
Sounds resolved then. 👍

**Closed by osm0sis** 2020-09-22 20:51 UTC
Labels: bug
