### ISSUE TITLE
Android 9 failed to swipe the gapps package

### ISSUE THREAD

**Issue by scarlet-glass** [opengapps/opengapps#720] opened 2019-02-18 06:23 UTC
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)
-------------------------------------------------------------------------------
device：redmagic mars  （NX619J）
version：Android 9
cpu：SDM845

log：

正在安装 Zip 刷机包 '/sdcard/open_gapps-arm64-9.0-pico-20190209.zip'
正在检测 Digest…
跳过 Digest 校验：未找到 Digest 文件
I:Update binary zip
Verifying package compatibility...
Package doesn't contain compatibility.zip entry
I:Zip does not contain SELinux file_contexts file in its root.
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/app_densities.txt
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/app_sizes.txt
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/bkup_tail.sh
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/gapps-remove.txt
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/g.prop
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/installer.sh
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/busybox-arm
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/tar-arm
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/unzip-arm
Archive:  /sdcard/open_gapps-arm64-9.0-pico-20190209.zip
  inflating: /tmp/zip-arm
 
##############################
  _____   _____   ___   ____  
 /  _  \ |  __ \ / _ \ |  _ \ 
|  / \  || |__) | |_| || | \ \
| |   | ||  ___/|  __/ | | | |
|  \ /  || |    \ |__  | | | |
 \_/ \_/ |_|     \___| |_| |_|
       ___   _   ___ ___  ___ 
      / __| /_\ | _ \ _ \/ __|
     | (_ |/ _ \|  _/  _/\__ \
      \___/_/ \_\_| |_|  |___/
##############################
 
Open GApps pico 9.0 - 20190209
 
- Mounting  /system /vendor
 
- Gathering device & ROM information
 
***** Incompatible Device Detected *****
 
This Open GApps package cannot be
installed on this device's architecture.
Please download the correct version for
your device: arm
 
******* GApps Installation failed *******
 
- Copying Log to /sdcard
 
- NO changes were made to your device
 
Installer will now exit...
 
Error Code: 64
E:[MTP] MyMtpDatabase::getObjectPropertyList MTP_RESPOSNE_INVALID_OBJECT_HANDLE 52
cp: can't stat '': No such file or directory
cp: can't stat '/system/etc/g.prop': Too many levels of symbolic links
cp: can't stat '/system/build.prop': No such file or directory
cp: can't stat '/data/local.prop': No such file or directory
cp: can't stat '/build.prop': No such file or directory
/tmp/installer.sh: line 1: logcat: Too many levels of symbolic links
- Unmounting  /system /vendor
 
linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/toybox" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
WARNING: linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/toybox" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
Updater 过程结束，错误：64
I:Install took 11 second(s).
安装 Zip 刷机包 '/sdcard/open_gapps-arm64-9.0-pico-20190209.zip' 时出错
正在更新分区详情…

**Comment by andrekugland-oplen** [comment] 2019-03-23 08:32
Hello, @scarlet-glass 

I unzipped the OpenGapps file and removed the check from the installer. It turned out that it worked OK when I finally booted.

Here are the lines I removed

`# Check to make certain user has proper version ROM Installed
if [ ! "$rom_build_sdk" = "$req_android_sdk" ]; then
  ui_print "*** Incompatible Android ROM detected ***";
  ui_print " ";
  ui_print "This GApps pkg is for Android $req_android_version.x ONLY";
  ui_print "Please download the correct version for"
  ui_print "your ROM: $(get_prop "ro.build.version.release") (SDK $rom_build_sdk)"
  ui_print " ";
  ui_print "******* GApps Installation failed *******";
  ui_print " ";
  install_note="${install_note}rom_android_version_msg"$'\n'; # make note that ROM Version is not compatible with these GApps
  abort "$E_ROMVER";
fi;

# Check to make certain that user device matches the architecture
device_architecture="$(get_prop "ro.product.cpu.abilist")"
# If the recommended field is empty, fall back to the deprecated one
if [ -z "$device_architecture" ]; then
  device_architecture="$(get_prop "ro.product.cpu.abi")"
fi

case "$device_architecture" in
  *x86_64*) arch="x86_64"; libfolder="lib64";;
  *x86*) arch="x86"; libfolder="lib";;
  *arm64*) arch="arm64"; libfolder="lib64";;
  *armeabi*) arch="arm"; libfolder="lib";;
  *) arch="unknown";;
esac

for targetarch in arm64 abort; do
  if [ "$arch" = "$targetarch" ]; then
    if [ "$libfolder" = "lib64" ]; then #on 64bit we also need to install 32 bit libs from the fbarch
      get_fallback_arch "$arch"
      fbarch="$fallback_arch"
    else
      fbarch=""
    fi
    break
  elif [ "abort" = "$targetarch" ]; then
    ui_print "***** Incompatible Device Detected *****"
    ui_print " "
    ui_print "This Open GApps package cannot be"
    ui_print "installed on this device's architecture."
    ui_print "Please download the correct version for"
    ui_print "your device: $arch"
    ui_print " "
    ui_print "******* GApps Installation failed *******"
    ui_print " "
    install_note="${install_note}arch_compat_msg"$'\n' # make note that Open GApps are not compatible with architecture
    abort "$E_ARCH"
  fi
done`

**Comment by darkmorpher** [comment] 2019-05-14 02:40
Duplicate of #491

**Comment by sideeffffect** [comment] 2019-12-07 15:44
Same issue on Xiaomi Redmi 7 and `open_gapps-arm-9.0-pico-20191127`. The phone is `arm64`, but OpenGApps complains that it is `arm`.

**Comment by sideeffffect** [comment] 2019-12-08 00:43
using different recovery worked: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1070#issuecomment-562900489

**Comment by osm0sis** [comment] 2020-08-18 23:39
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Closed by osm0sis** 2020-08-18 23:39 UTC
