### ISSUE TITLE
probleme when compilling

### ISSUE THREAD

**Issue by bchanot** [opengapps/opengapps#782] opened 2019-11-06 23:55 UTC
Hi, I have an issue when i compile the AOSP project with opengapps:

```
[vendor/opengapps/sources/x86/app/com.google.android.videos/23/nodpi/41600186.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  vendor/opengapps/sources/x86/app/com.google.android.videos/23/nodpi/41600186.apk may be a plain executable, not an archive
zipinfo:  cannot find zipfile directory in one of vendor/opengapps/sources/x86/app/com.google.android.videos/23/nodpi/41600186.apk or
          vendor/opengapps/sources/x86/app/com.google.android.videos/23/nodpi/41600186.apk.zip, and cannot find vendor/opengapps/sources/x86/app/com.google.android.videos/23/nodpi/41600186.apk.ZIP, period.
```
I tried anything and downloaded it 3 times, 3 times same problem. I don't know what to do. It is for all OpenGapps apks.

**Comment by sevenrock** [comment] 2019-11-07 05:49
Duplicate of https://github.com/opengapps/aosp_build/issues/229

**Closed** 2020-08-18 23:14 UTC
Labels: duplicate
