### ISSUE TITLE
Lineage 18 Update, removes GApp

### ISSUE THREAD

**Issue by arminabsalan** [opengapps/opengapps#920] opened 2021-05-30 01:15 UTC
I have a Note 3 SM-N9005 on which I have installed Lineage 18.1 (Android 11).
After installing the ROM on the device, then I installed the Open GApps with the help of it's config file.
After installing the Lineage **update** from the settings, all apps that previously installed by Open GApps were removed and the stock apps (AOSP) were installed!
I attached the config file. would you please help me that what can I do to update Lineage without any change in apps?
[gapps-config.txt](https://github.com/opengapps/opengapps/files/6565529/gapps-config.txt)

**Comment by lukasz1992** [comment] 2021-05-30 08:09
Android 11 is not supported yet. You can try these builds: https://sourceforge.net/projects/opengapps/files/arm64/test/20210513/

**Comment by arminabsalan** [comment] 2021-05-30 08:16
I used super package from this link:
[https://sourceforge.net/projects/opengapps/files/arm/test/20210130/](url)
Is it right?

**Comment by lukasz1992** [comment] 2021-06-05 07:02
@ccoenen
1. including Android Auto?
2. another thing to check is to flash newer version of LineageOS 18.1 (wait 1 week for new update) and check wether opengapps are still correctly installed.

**Comment by arminabsalan** [comment] 2021-06-07 06:25
thank you @ccoenen. but, is note 3 arm64 or arm structure?

**Comment by ccoenen** [comment] 2021-06-07 22:22
There are a few devices that go by that name. Namely the [Mi Note 3 (codename jason)](https://wiki.lineageos.org/devices/jason), the [Redmi Note 3 (codename kenzo)](https://wiki.lineageos.org/devices/kenzo) and the old [Samsung Galaxy Note 3 (codename ha3g)](https://wiki.lineageos.org/devices/ha3g).

According to the lineageos wiki page (all three linked above), the Mi / Redmi models from 2016 and 2017 are arm64. The 2013 Samsung one is not.

**Comment by ccoenen** [comment] 2021-06-07 22:50
>     1. including Android Auto?

Sorry, I have no way of testing it.

>     2. another thing to check is to flash newer version of LineageOS 18.1 (wait 1 week for new update) and check wether opengapps are still correctly installed.

I did an update just now, and I believe everything is fine.

**Comment by arminabsalan** [comment] 2021-06-09 10:27
> There are a few devices that go by that name. Namely the [Mi Note 3 (codename jason)](https://wiki.lineageos.org/devices/jason), the [Redmi Note 3 (codename kenzo)](https://wiki.lineageos.org/devices/kenzo) and the old [Samsung Galaxy Note 3 (codename ha3g)](https://wiki.lineageos.org/devices/ha3g).
> 
> According to the lineageos wiki page (all three linked above), the Mi / Redmi models from 2016 and 2017 are arm64. The 2013 Samsung one is not. Look for "architecture" in the specifications on the right side of every wiki page.

I installed nano version in TWRP, it return error 64, that my device is not arm64 structure, it is arm structure.

**Comment by ccoenen** [comment] 2021-06-09 11:23
Yes, the Samsung Galaxy Note 3 is an arm device, not arm64. Sorry, I missed that detail in the initial post. I do have a different phone myself, so that's why I went with arm64 for mine.

**Comment by arminabsalan** [comment] 2021-06-09 14:00
With all this, thank you for taking the time @ccoenen .

**Comment by osm0sis** [comment] 2021-07-19 02:41
My guess is this device/ROM uses /product partition, which Open GApps supports for install, but the addon.d doesn't support restoring them until it can be updated to addon.d-v3.

Known issue, duplicate of #872 :+1:

**Closed by osm0sis** 2021-07-19 02:41 UTC
Labels: duplicate
