### ISSUE TITLE
Open Gaps 9.0 boot loop 

### ISSUE THREAD

**Issue by neobuddy89** [opengapps/opengapps#799] opened 2020-01-26 05:32 UTC
Open Gaps 9.0 Arm64 Nano 17th Jan boots fine.

Open Gaps 9.0 Arm64 Nano 23rd and 24th Jan bootloops with below error:

01-26 05:08:58.016 25430 25430 E System  : ******************************************
01-26 05:08:58.017 25430 25430 E System  : ************ Failure starting system services
01-26 05:08:58.017 25430 25430 E System  : java.lang.SecurityException: Permission android.permission.REQUEST_NETWORK_SCORES is not a changeable permission type
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:383)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.PackageManagerService$PackageManagerInternalImpl.grantRuntimePermission(PackageManagerService.java:24282)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1416)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1311)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissionExceptions(DefaultPermissionGrantPolicy.java:1500)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissions(DefaultPermissionGrantPolicy.java:271)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21350)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1797)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:463)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:312)
01-26 05:08:58.017 25430 25430 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-26 05:08:58.017 25430 25430 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)
01-26 05:08:58.017 25430 25430 E Zygote  : System zygote died with exception
01-26 05:08:58.017 25430 25430 E Zygote  : java.lang.SecurityException: Permission android.permission.REQUEST_NETWORK_SCORES is not a changeable permission type
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:383)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.PackageManagerService$PackageManagerInternalImpl.grantRuntimePermission(PackageManagerService.java:24282)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1416)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1311)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissionExceptions(DefaultPermissionGrantPolicy.java:1500)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissions(DefaultPermissionGrantPolicy.java:271)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21350)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1797)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.SystemServer.run(SystemServer.java:463)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.server.SystemServer.main(SystemServer.java:312)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at java.lang.reflect.Method.invoke(Native Method)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-26 05:08:58.017 25430 25430 E Zygote  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)
01-26 05:08:58.017 25430 25430 D AndroidRuntime: Shutting down VM
01-26 05:08:58.017 25430 25430 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
01-26 05:08:58.017 25430 25430 E AndroidRuntime: java.lang.SecurityException: Permission android.permission.REQUEST_NETWORK_SCORES is not a changeable permission type
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:383)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService$PackageManagerInternalImpl.grantRuntimePermission(PackageManagerService.java:24282)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1416)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1311)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissionExceptions(DefaultPermissionGrantPolicy.java:1500)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissions(DefaultPermissionGrantPolicy.java:271)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21350)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1797)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:463)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:312)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-26 05:08:58.017 25430 25430 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)

**Comment by nezorflame** [comment] 2020-01-26 13:43
Hi! Thanks for your feedback.
We're aware of this and will push a fix today.
Would you like to flash a test build to confirm that the fix works before we publish it?

**Comment by nezorflame** [comment] 2020-01-26 13:46
Also a duplicate of https://github.com/opengapps/opengapps/issues/755

**Comment by nezorflame** [comment] 2020-01-26 15:24
Please try this test build to see if it fixes your setup: https://sourceforge.net/projects/opengapps/files/arm64/test/open_gapps-arm64-9.0-nano-20200126-FIXED.zip/download

**Comment by ArnauBG** [comment] 2020-01-27 16:07
> Open Gaps 9.0 Arm64 Nano 17th Jan boots fine.
> 
> Open Gaps 9.0 Arm64 Nano 23rd and 24th Jan bootloops with below error:
> 
> 01-26 05:08:58.016 25430 25430 E System : ******************************************
> 01-26 05:08:58.017 25430 25430 E System : ************ Failure starting system services
> 01-26 05:08:58.017 25430 25430 E System : java.lang.SecurityException: Permission android.permission.REQUEST_NETWORK_SCORES is not a changeable permission type
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:383)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.PackageManagerService$PackageManagerInternalImpl.grantRuntimePermission(PackageManagerService.java:24282)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1416)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1311)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissionExceptions(DefaultPermissionGrantPolicy.java:1500)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissions(DefaultPermissionGrantPolicy.java:271)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21350)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.SystemServer.startOtherServices(SystemServer.java:1797)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.SystemServer.run(SystemServer.java:463)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.server.SystemServer.main(SystemServer.java:312)
> 01-26 05:08:58.017 25430 25430 E System : at java.lang.reflect.Method.invoke(Native Method)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 01-26 05:08:58.017 25430 25430 E System : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)
> 01-26 05:08:58.017 25430 25430 E Zygote : System zygote died with exception
> 01-26 05:08:58.017 25430 25430 E Zygote : java.lang.SecurityException: Permission android.permission.REQUEST_NETWORK_SCORES is not a changeable permission type
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:383)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.PackageManagerService$PackageManagerInternalImpl.grantRuntimePermission(PackageManagerService.java:24282)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1416)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1311)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissionExceptions(DefaultPermissionGrantPolicy.java:1500)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissions(DefaultPermissionGrantPolicy.java:271)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21350)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.SystemServer.startOtherServices(SystemServer.java:1797)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.SystemServer.run(SystemServer.java:463)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.server.SystemServer.main(SystemServer.java:312)
> 01-26 05:08:58.017 25430 25430 E Zygote : at java.lang.reflect.Method.invoke(Native Method)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 01-26 05:08:58.017 25430 25430 E Zygote : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)
> 01-26 05:08:58.017 25430 25430 D AndroidRuntime: Shutting down VM
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: java.lang.SecurityException: Permission android.permission.REQUEST_NETWORK_SCORES is not a changeable permission type
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:383)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.PackageManagerService$PackageManagerInternalImpl.grantRuntimePermission(PackageManagerService.java:24282)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1416)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantRuntimePermissions(DefaultPermissionGrantPolicy.java:1311)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissionExceptions(DefaultPermissionGrantPolicy.java:1500)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissions(DefaultPermissionGrantPolicy.java:271)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21350)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.SystemServer.startOtherServices(SystemServer.java:1797)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.SystemServer.run(SystemServer.java:463)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.server.SystemServer.main(SystemServer.java:312)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 01-26 05:08:58.017 25430 25430 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)

Same problem with tvstock ARM32 versions.

**Comment by nezorflame** [comment] 2020-01-28 18:08
@ArnauBG does it happen on a latest build?

**Comment by ArnauBG** [comment] 2020-01-28 18:42
Yes, the build tvstock 20200128.

**Comment by nezorflame** [comment] 2020-01-30 09:26
@neobuddy89 was that issue fixed for you in the latest builds? I want to understand if the new problem is purely tvstock-specific.

**Comment by nezorflame** [comment] 2020-01-31 12:16
Please check on the new builds from January 31 to see if the issue is resolved.

**Comment by ArnauBG** [comment] 2020-01-31 18:24
@nezorflame I tried to install the January 31 release of OpenGApps-TVStock and I still experiencing boot-loop.

**Comment by nezorflame** [comment] 2020-01-31 18:45
@ArnauBG same error as before? `android.permission.REQUEST_NETWORK_SCORES`

**Comment by ArnauBG** [comment] 2020-01-31 19:13
@nezorflame I dont know since I cant acces adb for catlog. My device is not supporting connectind to a computer.

**Comment by ArnauBG** [comment] 2020-02-08 22:52
Hi @nezorflame I seen the pull request that mencioned this issue, that says that the boot-loop will be solved. I download the OpenGApps-TVStock February 8 release, and my device 
takes more than an hour in boot-loop and still trying to boot. I think that in my case (at least) it still boot-looping.

Thanks.

**Comment by ArnauBG** [comment] 2020-02-09 19:14
I get the cat-log. I give you a Github Gist URL beacause is so big the log and I don't know where can be the problem.

[Here's my cat-log](https://gist.github.com/ArnauBG/bbf92fa291f815214a3e631b9e9cd057)

Thanks

**Comment by ArnauBG** [comment] 2020-02-09 19:14
@nezorflame I get the cat-log. I give you a Github Gist URL beacause is so big the log and I don't know where can be the problem.

[Here's my cat-log](https://gist.github.com/ArnauBG/bbf92fa291f815214a3e631b9e9cd057)

Thanks

**Closed** 2020-08-18 23:12 UTC
