### ISSUE TITLE
DARK SCREEN WHEN CREATING GOOGLE ACCOUNT. 

### ISSUE THREAD

**Issue by McZI** [opengapps/opengapps#820] opened 2020-03-22 18:42 UTC
I used TWRP 3.3.1-0 to flash open_gapps-arm-9.0-stock-20200322.zip after reboot, can't sign into Google play store, screen goes dark when I try adding a Google account. Need help on the right open Gapps for my HTC One M8.
- CPU architecture **ARMv7 Processor rev 1 (v71)**

**Comment by imiimiimi** [comment] 2020-03-26 14:07
i used **open_gapps-arm-9.0-aroma-20200325** for LG G2 and have same problem, it seems it's because of GAPPS remove stock Browser (even if set dont remove it) and dont install Chrome.

**Comment by imiimiimi** [comment] 2020-03-26 22:04
i extracted Chrome from package and tested it, but couldnt install it, it seems file has a problem.
if dont select Chrome, problem doesnt appear.

**Comment by chincheta0815** [comment] 2020-04-05 05:19
I got the same issue. Using the open_gapps-arm-10-[nano|pico]-202004[0304].zip with lineageos from the same days.
Interestingly everything worked using a different copy-partitions scipt:
While the official script mentioned by lineageos in the install instructions does not work and cause a black screen [copy-partitions.zip](https://androidfilehost.com/?fid=4349826312261712574), this one did not cause the black screen [copy-partitions-AB.zip](https://drive.google.com/open?id=1fJf5jwFFeMZTGzBJYF38oZ4V2PprG77D) worked. The only difference between these are the names of the partitions that are ignored while copying...

**Comment by a-hab** [comment] 2020-04-09 15:50
Same issue here for me, but on android 10 with latest lineage-recovery on "moto g7 plus".

opengapps-version I tested: 
* open_gapps-arm64-10.0-pico-20200408.zip
* open_gapps-arm64-10.0-nano-20200408.zip
* open_gapps-arm64-10.0-micro-20200408.zip

recovery:
* lineage-17.1-20200406-recovery-lake.img

android:
* lineage-17.1-20200408-nightly-lake-signed.zip

**Comment by kapoorlakshya** [comment] 2020-08-09 16:54
Still experiencing this on OnePlus 3T (`arm64`)  with Havoc OS 3.7 (Android 10) and the Aroma installer.

Anyone have a workaround for this?

**Comment by nezorflame** [comment] 2020-08-16 19:39
This might be related to Webview.
Can someone try to reproduce this on a latest release, but with logcat enabled?

**Comment by nezorflame** [comment] 2020-08-16 23:13
@kapoorlakshya as for the "OK Google" error, it should be fixed since the August 14 build.

**Comment by kapoorlakshya** [comment] 2020-08-16 23:17
@nezorflame Oh cool! Thanks! All I need to do is dirty flash GApps Aroma. Right?

**Comment by nezorflame** [comment] 2020-08-16 23:33
Yeah, dirty flash is fine.
It fixes itself with the Google app update anyway, but we ship a correct version out of the box as well now.

**Comment by kapoorlakshya** [comment] 2020-08-17 07:57
@nezorflame Yup, looks like the update via the Play store fixed it. Thanks for letting me know!

**Comment by nezorflame** [comment] 2020-08-17 13:28
The issue with dark screen still needs confirmation, I'd be glad if someone could assist me with reproducing this and taking the logcat.

**Comment by osm0sis** [comment] 2020-09-08 13:50
If nobody will confirm and provide a logcat we'll have to close this as abandoned.

**Closed** 2020-09-12 02:53 UTC
Labels: bug, help wanted
