### ISSUE TITLE
error executing updater binary in zip (Lollipop-x86)

### ISSUE THREAD

**Issue by shinjitsunokami** [opengapps/opengapps#370] opened 2016-10-31 17:23 UTC
Trying Mini-Package on Zenfone 4 (A400CG - Lollipop 5.0)
Can't install anything but Google's Core.

[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/562411/open_gapps_log.txt)
[recovery.txt](https://github.com/opengapps/opengapps/files/562418/recovery.txt)

**Comment by mfonville** [comment] 2016-10-31 18:01
duplicate of #367

**Closed by mfonville** 2016-10-31 18:01 UTC
