### ISSUE TITLE
Cannot finish new user wizard with nano gapps

### ISSUE THREAD

**Issue by fossum** [opengapps/opengapps#184] opened 2015-12-07 20:49 UTC
Seems the nano gapps cannot pass the "Tap & Go" page in the new user dialog. Crashes with some sort of NoSuchMethodException (using CM12.1)

**Comment by davepwsmith** [comment] 2015-12-08 12:32
Probably the same as #179

**Comment by julienbrunet** [comment] 2015-12-08 14:57
Same issue here. 
Actually you can pass the Tap&Go screen by completing the wizard without any internet connection (no wifi or data).
By then cyanogen wil start correctly but no to start any google application (No Suche Method Exception, Invalid Reflection...)

**Comment by mfonville** [comment] 2015-12-08 15:59
Yes, this is a duplicate of #184, so I close this bug and keep an eye on that one instead.
I wrote a fix that hopefully solves it. I barely do have time for personal reasons though, so sorry for slow responses.

**Closed by mfonville** 2015-12-08 15:59 UTC
