### ISSUE TITLE
Google Chrome Language Bug

### ISSUE THREAD

**Issue by dontobi** [opengapps/opengapps#731] opened 2019-03-31 17:36 UTC
I have a package installed with the Chrome browser. Now the UI of the Chrome browser is displayed in english. So I installed the Chrome Beta Browser. in the folder /data/app is an APK with the title split_config.de.apk. Maybe this file needs to be installed for the specific national language in the future.

**Comment by Anubioz** [comment] 2019-05-15 14:31
Same issue here

**Comment by suiahaw** [comment] 2019-05-16 11:30
I can't change the chrome display language to Chinese either.

**Comment by yurikoles** [comment] 2019-06-20 17:41
Duplicate of #675. @dontobi please close this.

**Comment by julolosvalles26** [comment] 2019-06-21 14:48
I see that there is no one working on the problem, maybe it will correct itself only when detecting duplicates of post, I do not think he heh je gives the same use another pack gapps and the rest I install it as user

**Closed** 2019-07-30 07:07 UTC
