### ISSUE TITLE
error 255 on redmi note7pro devices with aroma arm64 package

### ISSUE THREAD

**Issue by OdinShiva** [opengapps/opengapps#757] opened 2019-08-16 06:41 UTC
as describe in title

**Comment by r33int** [comment] 2019-08-22 09:10
Can confirm on rn7 too. It's asking for an arm package, even though the soc is arm64.
Log:
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/3529261/open_gapps_log.txt)

**Comment by curiousrom** [comment] 2019-12-06 22:57
@OdinShiva - Could you give more troubleshooting info like your exact recovery version & ROM name & version please? A log would be helpful too.

Same questions to @r33int & thanks for the log.

**Comment by osm0sis** [comment] 2020-08-18 23:21
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Comment by subtank** [comment] 2020-12-05 02:25
2020-12-04 version still get this problem, xiaomi MIX3 with stock rom @Android 10 and Last TWRP version 3.4.0

**Comment by osm0sis** [comment] 2020-12-05 18:57
Does your TWRP have the wrong architecture listed?

**Comment by osm0sis** [comment] 2021-02-19 12:40
Reclosing this if @subtank can't supply useful current information, or others can't corroborate this on latest builds with logs.

**Comment by tokenwizard** [comment] 2021-06-14 16:07
I can confirm this is still an issue on Xiaomi Mi 9 (cepheus) with LineageOS 17.1 using TWRP version 3.5.2_9-0

I've done a fresh install of the ROM from TWRP and then on trying to install opengapps using the aroma package, I get error 255.

Looks like a Memory issue. In the log there is a fatal error that says "Out of Memory."

This package is a whopping 1.6GB, outweighing even the entire LineageOS ROM, so that could have something to do with it. 

Relevant log section here:
`Installing zip file '/sdcard/open_gapps-arm64-10.0-aroma-20210610.zip'
Unmounting System...
I:Update binary zip
Verifying package compatibility...
Package doesn't contain compatibility.zip entry
I:Extracting updater binary 'META-INF/com/google/android/update-binary'
I:Zip does not contain SELinux file_contexts file in its root.
I:has_legacy_properties: Found legacy property match!
I:Legacy property environment initialized.
aroma/s: Initializing
Starting AROMA Installer version 2.70RC2
     (c) 2013 by amarullz xda-developers

Starting AROMA Installer version 2.70RC2
(c) 2013 by amarullz xda-developers

aroma/s: Mute Parent
aroma/s: Saving Arguments
aroma/s: Open Archive
aroma/s: Initializing Resource
aroma/s: INDR Input Device: gpio-keys (event3) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: qti-haptics (event1) - Class : 0
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: uinput-goodix (event2) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: qpnp_pon (event0) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: fts (event4) - Class : 7
aroma/s:   VKN : 0, CALIB : (0,1079,0,2339)
aroma/s: Starting Interface
E:[MTP] request read returned -1, errno: 5Loading PNG : META-INF/com/google/android/aroma/fonts/small.png
Loading PNG : META-INF/com/google/android/aroma/fonts/small.png OK
aroma/e: PNG FONT(META-INF/com/google/android/aroma/fonts/small.png): Not Supported. Only 8 Bit Depth with 4 Channel.
Loading PNG : META-INF/com/google/android/aroma/fonts/big.png
Loading PNG : META-INF/com/google/android/aroma/fonts/big.png OK
aroma/e: PNG FONT(META-INF/com/google/android/aroma/fonts/big.png): Not Supported. Only 8 Bit Depth with 4 Channel.


aroma/FATAL-ERROR: Out Of Memory...


Updater process ended with ERROR: 255
I:Legacy property environment disabled.
I:Install took 4 second(s).
Error installing zip file '/sdcard/open_gapps-arm64-10.0-aroma-20210610.zip'`

**Comment by PizzaG** [comment] 2021-12-10 06:45
I am having this issue as well on S10+, do we have a fix for this error?

**Comment by osm0sis** [comment] 2023-01-22 00:02
aroma is deprecated.

**Closed by osm0sis** 2023-01-22 00:02 UTC
Labels: bug, help wanted
